"""Differential test: the orchestrated BIODIV run must reproduce BOTH legacy
routes exactly, the compute route (observed scores) and the impute route
(imputed scores), on the committed UN fixtures.

``biodiv_imputation_cases.json`` was generated by ``generate_imputation_cases.py``
in the old virtualenv at the pinned commit. The Austria rows record the
executable legacy behaviour for a landlocked country (marine filled from the
reference class, three components averaged), which conflicts with the retired
2018 static metadata; that conflict is preserved, not resolved, here.
"""

import json
from pathlib import Path

import pytest

from sspi.imputation import is_imputed
from sspi.indicators import compute_indicator, registry
from sspi.ingestion.unsdg import normalize_unsdg_dataset
from sspi.metadata import MetadataCatalog
from sspi.scoring import Observation

HERE = Path(__file__).parent
BIODIV = json.loads((HERE / "biodiv_imputation_cases.json").read_text())
FIXTURES = HERE.parent / "fixtures" / "unsdg"
THINNED_MYS_MARINE_YEARS = set(range(2000, 2003)) | {2010, 2011, 2015} | set(range(2022, 2026))


def slim(o: Observation) -> dict:
    return {
        "dataset_code": o.dataset_code,
        "country_code": o.country_code,
        "year": o.year,
        "value": o.value,
        "unit": o.unit,
        "imputed": bool(o.provenance.get("imputed", False)),
        "imputation_method": o.provenance.get("imputation_method"),
        "imputation_distance": o.provenance.get("imputation_distance"),
    }


def as_records(scores):
    return [
        {"country_code": s.country_code, "year": s.year, "score": s.score, "unit": s.unit, "inputs": sorted((slim(o) for o in s.inputs), key=lambda x: x["dataset_code"])}
        for s in sorted(scores, key=lambda s: (s.country_code, s.year))
    ]


@pytest.fixture(scope="module")
def observations():
    catalog = MetadataCatalog.load()
    payload = {
        "14.5.1": json.loads((FIXTURES / "14_5_1_sample.json").read_text())["data"],
        "15.1.2": json.loads((FIXTURES / "15_1_2_sample.json").read_text())["data"],
    }
    return [
        o
        for code in ("UNSDG_MARINE", "UNSDG_TERRST", "UNSDG_FRSHWT")
        for o in normalize_unsdg_dataset(catalog.dataset(code), payload[catalog.dataset(code).source.query_code]).observations
    ]


def variant_observations(observations, variant):
    if variant["name"] == "thinned_mys_marine":
        return [o for o in observations if not (o.dataset_code == "UNSDG_MARINE" and o.country_code == "MYS" and o.year in THINNED_MYS_MARINE_YEARS)]
    return observations


@pytest.mark.parametrize("variant", BIODIV["variants"], ids=[v["name"] for v in BIODIV["variants"]])
def test_orchestrated_run_matches_both_legacy_routes(observations, variant):
    result = compute_indicator(registry.get("BIODIV"), variant_observations(observations, variant), variant["recipients"])

    assert as_records(result.observed_scores) == variant["observed_scores"]  # legacy compute route
    assert as_records(result.imputed_scores) == variant["imputed_scores"]  # legacy impute route after filter_imputations
    assert sorted({(u.country_code, u.year) for u in result.unscored}) == [tuple(x) for x in variant["incomplete_identities"]]

    observed = {(s.country_code, s.year) for s in result.observed_scores}
    imputed = {(s.country_code, s.year) for s in result.imputed_scores}
    assert observed.isdisjoint(imputed)
    assert sorted(observed) == [tuple(x) for x in variant["observed_only_scores_not_stored_by_impute_route"]]
    assert all(not is_imputed(s) for s in result.observed_scores) and all(is_imputed(s) for s in result.imputed_scores)
    # the compute route's incomplete groups are exactly the raw identities it could not score
    raw = {(o.country_code, o.year) for o in variant_observations(observations, variant)}
    assert sorted(raw - observed) == [tuple(x) for x in variant["observed_incomplete_identities"]]


def test_headline_values_austria_and_malaysia(observations):
    committed = next(v for v in BIODIV["variants"] if v["name"] == "fixture_as_committed")
    thinned = next(v for v in BIODIV["variants"] if v["name"] == "thinned_mys_marine")
    definition = registry.get("BIODIV")

    run = compute_indicator(definition, observations, committed["recipients"])
    scores = {(s.country_code, s.year): s for s in run.scores}
    aut_2020 = scores[("AUT", 2020)]
    marine = next(o for o in aut_2020.inputs if o.dataset_code == "UNSDG_MARINE")
    assert is_imputed(aut_2020) and marine.provenance["imputation_method"] == "ImputeReferenceClassAverage"
    assert marine.value == 36.56867346153846 and aut_2020.score == 0.5858737782051282
    assert sorted(y for c, y in scores if c == "AUT") == list(range(2000, 2024))
    mys_2020 = scores[("MYS", 2020)]
    assert not is_imputed(mys_2020) and mys_2020.score == 0.2972865333333333
    assert sorted(y for c, y in scores if c == "MYS") == list(range(2000, 2026))  # compute route: no year filter
    assert is_imputed(scores[("CHE", 2020)]) and scores[("CHE", 2020)].score == 0.40930980448717946

    run = compute_indicator(definition, variant_observations(observations, thinned), thinned["recipients"])
    scores = {(s.country_code, s.year): s for s in run.scores}
    assert (scores[("MYS", 2001)].score, scores[("MYS", 2011)].score, scores[("MYS", 2023)].score) == (0.18463580000000002, 0.2613001111111111, 0.2972865333333333)
    assert all(is_imputed(scores[("MYS", y)]) for y in (2001, 2011, 2023)) and not is_imputed(scores[("MYS", 2020)])
    assert scores[("AUT", 2020)].score == 0.593088010283688
