"""Parity for NRGINT and AIRPOL against BOTH legacy routes on the committed
UN SDG rows: observed scores (compute route), imputed scores (impute route:
extrapolation of scores, and for AIRPOL the reference-class mean of scores),
units, identities and classification.

``nrgint_cases.json`` and ``airpol_cases.json`` were generated by
``generate_energy_cases.py`` in the old virtualenv at the pinned commit,
running the legacy cleaners and the ``compute_*`` / ``impute_*`` view
functions themselves. Every comparison is exact; no tolerance.

ALTNRG, the third Energy indicator, has its own module,
``test_golden_altnrg.py``.
"""

from collections import Counter

import pytest

from sspi.errors import DuplicateObservationError
from sspi.imputation import is_imputed
from sspi.indicators import airpol, compute_indicator, nrgint, registry
from sspi.indicators.strategy import ExtrapolateScores
from sspi.ingestion import SUPPORTED_DATASETS
from sspi.ingestion.unsdg import normalize_unsdg_dataset
from sspi.metadata import CountryCatalog, DatasetMetadata, MetadataCatalog, SourceMetadata
from tests.golden.energy import CASES, normalized, observations, rows
from tests.golden.parity import INDICATOR_CASES, INTENTIONAL_DIVERGENCES, PENDING_METHODOLOGY_DECISIONS, assert_parity, legacy_inconsistency, load_cases, score_level_records

SSPI67 = tuple(CountryCatalog.load().group("SSPI67").members)
EXPECTED = {
    "NRGINT": {"formula": "goalpost(UNSDG_NRGINT, 15, 0)", "goalposts": [15, 0], "observed": 598, "imputed": {"Forward Extrapolation": 1}},
    "AIRPOL": {"formula": "goalpost(UNSDG_AIRPOL, 40, 0)", "goalposts": [40, 0], "observed": 196, "imputed": {"Backward Extrapolation": 140, "ImputeReferenceClassAverage": 1272}},
}
FIXTURE_COUNTRIES = {"ALB", "AUT", "BRA", "CHE", "CHN", "DEU", "IND", "JPN", "KEN", "MYS", "NGA", "SGP", "USA", "ZAF"}


@pytest.fixture(scope="module", params=sorted(CASES))
def case(request):
    code = request.param
    return code, load_cases(INDICATOR_CASES[code]), compute_indicator(registry.get(code), observations(code), SSPI67)


def test_golden_file_records_the_legacy_facts(case):
    code, golden, _ = case
    definition, expected = registry.get(code), EXPECTED[code]
    definition.check_against(MetadataCatalog.load())
    assert golden["indicator_code"] == code and golden["impute_route_exists"] is True and definition.imputes
    assert golden["formula"] == expected["formula"] and golden["goalposts"] == expected["goalposts"] == list(definition.goalposts)
    assert golden["unit"] == "Index" == definition.unit  # both legacy routes write the same literal
    assert definition.dataset_codes == (CASES[code][0],) and definition.score_dependencies == () and definition.auxiliary_datasets == ()
    strategy, extrapolation = definition.imputation, golden["score_extrapolation"]
    assert isinstance(strategy, ExtrapolateScores)
    assert (strategy.forward_to, strategy.backward_to) == (extrapolation["forward_to"], extrapolation["backward_to"])
    reference = extrapolation["reference_class"]
    assert (strategy.recipient_group, strategy.reference_years) == ((reference["recipient_group"], tuple(reference["years"])) if reference else (None, None))


def test_methodology_text_agrees_with_the_executable_formula():
    assert load_cases(INDICATOR_CASES["AIRPOL"])["methodology_score_function"] == "Score = goalpost(UNSDG_AIRPOL, 40, 0)"
    assert load_cases(INDICATOR_CASES["NRGINT"])["methodology_score_function"] == "Score = goalpost(UNSDG_NRGINT, LowerGoalpost, UpperGoalpost)"
    assert "2017" in load_cases(INDICATOR_CASES["NRGINT"])["methodology_description"]  # NRGINT-1: the source now says 2021
    assert "PM2.5 and PM10) in cities" in load_cases(INDICATOR_CASES["AIRPOL"])["methodology_description"]  # AIRPOL-1


def test_legacy_output_is_consistent_so_exact_parity_is_required(case):
    code, golden, _ = case
    assert legacy_inconsistency(golden) is None
    assert golden["legacy_output_conflicts"] == {"observed_and_imputed": [], "duplicate_imputed": []}
    assert not any(c == code for c, _ in list(INTENTIONAL_DIVERGENCES) + list(PENDING_METHODOLOGY_DECISIONS))


def test_observed_scores_match_the_compute_route(case):
    code, golden, result = case
    assert_parity(f"{code} observed scores", score_level_records(result.observed_scores), golden["observed_scores"])
    assert len(result.observed_scores) == EXPECTED[code]["observed"] and not any(is_imputed(s) for s in result.observed_scores)
    assert all(s.provenance == {} and len(s.inputs) == 1 for s in result.observed_scores)


def test_imputed_scores_match_the_impute_route(case):
    code, golden, result = case
    assert_parity(f"{code} imputed scores", score_level_records(result.imputed_scores), golden["imputed_scores"])
    assert Counter(s.provenance["imputation_method"] for s in result.imputed_scores) == EXPECTED[code]["imputed"]
    assert all(is_imputed(s) for s in result.imputed_scores) and {s.unit for s in result.scores} == {"Index"}


def test_final_identity_set_and_classification(case):
    code, golden, result = case
    legacy = {(r["country_code"], r["year"]) for key in ("observed_scores", "imputed_scores") for r in golden[key]}
    identities = [(s.country_code, s.year) for s in result.scores]
    assert len(identities) == len(set(identities)) == len(legacy) and set(identities) == legacy
    assert result.unscored == ()
    assert not any(o.provenance.get("imputed") for s in result.scores for o in s.inputs)  # imputation is on the score, never on an observation


def test_nrgint_behaviour():
    result = compute_indicator(registry.get("NRGINT"), observations("NRGINT"))
    assert (min(s.year for s in result.observed_scores), max(s.year for s in result.observed_scores)) == (1990, 2024)  # no year filter
    (carried,) = result.imputed_scores  # the one country whose series stops before 2023
    assert (carried.country_code, carried.year, carried.provenance["source_year"], carried.provenance["imputation_distance"]) == ("VIR", 2023, 2022, 1)
    virgin_islands = {s.year: s for s in result.scores if s.country_code == "VIR"}
    assert carried.score == virgin_islands[2022].score and carried.inputs == virgin_islands[2022].inputs and min(virgin_islands) == 2002  # nothing carried backward
    assert {s.country_code for s in result.scores if s.year == 2024} == {"BTN", "SOM"}  # observed 2024 kept, nothing extrapolated past 2023
    scores = {(s.country_code, s.year): s for s in result.scores}
    austria = scores[("AUT", 2023)]
    assert austria.inputs[0].value == 2.13 and austria.score == nrgint.score_nrgint(2.13) == (2.13 - 15) / (0 - 15)
    assert min(s.score for s in result.scores) == 0.0 and scores[("CHN", 1990)].inputs[0].value == 19.58 and scores[("CHN", 1990)].score == 0.0  # above the lower goalpost: clamped to 0
    assert len({s.country_code for s in result.scores}) == 19 and normalized("NRGINT").missing_values == 618


def test_airpol_behaviour():
    result = compute_indicator(registry.get("AIRPOL"), observations("AIRPOL"), SSPI67)
    observed_countries = {s.country_code for s in result.observed_scores}
    assert observed_countries == FIXTURE_COUNTRIES and {s.year for s in result.observed_scores} == set(range(2010, 2024))
    by_method = {}
    for s in result.imputed_scores:
        by_method.setdefault(s.provenance["imputation_method"], []).append(s)
    backward, reference = by_method["Backward Extrapolation"], by_method["ImputeReferenceClassAverage"]
    assert {s.country_code for s in backward} == FIXTURE_COUNTRIES and {s.year for s in backward} == set(range(2000, 2010))
    scores = {(s.country_code, s.year): s for s in result.scores}
    assert all(s.score == scores[(s.country_code, 2010)].score and s.inputs == scores[(s.country_code, 2010)].inputs and s.provenance["source_year"] == 2010 for s in backward)  # AIRPOL-2
    recipients = sorted(set(SSPI67) - observed_countries)
    assert len(recipients) == 53 and sorted({s.country_code for s in reference}) == recipients == load_cases(INDICATOR_CASES["AIRPOL"])["reference_class_recipients"]
    assert {s.year for s in reference} == set(range(2000, 2024)) and len({s.score for s in reference}) == 1
    assert all(s.inputs == () and s.provenance["reference_score_count"] == 196 for s in reference)  # the mean of every observed score, any country, any year
    assert "ALB" not in SSPI67 and "ALB" in observed_countries  # a non-member is scored and enters the mean; it is never a recipient
    malaysia = scores[("MYS", 2023)]
    assert malaysia.score == airpol.score_airpol(malaysia.inputs[0].value) and not is_imputed(malaysia)
    assert max(s.inputs[0].value for s in result.observed_scores) > 40 and min(s.score for s in result.observed_scores) == 0.0  # clamped at the lower goalpost


def test_without_a_recipient_list_no_reference_class_score_is_produced():
    result = compute_indicator(registry.get("AIRPOL"), observations("AIRPOL"))
    assert Counter(s.provenance["imputation_method"] for s in result.imputed_scores) == {"Backward Extrapolation": 140}


def test_airpol_dataset_is_the_all_areas_slice_only():
    """The fixture carries all five location slices for four countries and World; the canonical ``location: ALLAREA`` keeps one."""
    catalog = MetadataCatalog.load()
    dataset = catalog.dataset("UNSDG_AIRPOL")
    assert dataset.source.dimensions == {"location": "ALLAREA"} and dataset.source.organization_series_code == "EN_ATM_PM25" and dataset.source.query_code == "11.6.2"
    assert Counter(row["location"] for row in rows("AIRPOL")) == {"ALLAREA": 17, "CITY": 5, "RURAL": 5, "TSUB": 5, "URBAN": 5}
    result = normalized("AIRPOL")
    assert len(result.observations) == 14 * 14 and {o.provenance["source_dimensions"]["location"] for o in result.observations} == {"ALLAREA"}
    assert {o.unit for o in result.observations} == {"mgr/m^3"} and [code for code, _ in result.skipped_areas] == ["2", "150", "1"]
    all_areas = {row["geoAreaCode"]: row for row in rows("AIRPOL") if row["location"] == "ALLAREA"}
    assert f'"value":"{next(o for o in result.observations if (o.country_code, o.year) == ("MYS", 2023)).value}"' in all_areas["458"]["years"].replace(": ", ":")
    unfiltered = DatasetMetadata(code=dataset.code, name=dataset.name, dataset_type=dataset.dataset_type, unit=dataset.unit, source=SourceMetadata(organization_code="UNSDG", query_code="11.6.2", organization_series_code="EN_ATM_PM25"))
    with pytest.raises(DuplicateObservationError, match="location"):
        normalize_unsdg_dataset(unfiltered, rows("AIRPOL"))


def test_nrgint_dataset_metadata_and_coverage():
    dataset = MetadataCatalog.load().dataset("UNSDG_NRGINT")
    assert (dataset.source.query_code, dataset.source.organization_series_code, dataset.source.dimensions, dataset.unit) == ("7.3.1", "EG_EGY_PRIM", None, "MJ_PER_GDP_CON_PPP_USD")
    result = normalized("NRGINT")
    assert len(result.observations) == 598 and {o.provenance["source_series"] for o in result.observations} == {"EG_EGY_PRIM"}
    assert {o.provenance["nature"] for o in result.observations} == {"E"}  # source flags are kept, never used to filter


def test_all_three_energy_indicators_are_executable_and_their_datasets_ingestible():
    catalog = MetadataCatalog.load()
    energy = sorted(i.code for i in catalog.indicators() if i.category_code == "NRG")
    assert energy == ["AIRPOL", "ALTNRG", "NRGINT"] and set(energy) <= set(registry.codes())
    assert {code for i in energy for code in catalog.indicator(i).dataset_codes} <= set(SUPPORTED_DATASETS)
