"""Score parity: the orchestrated CHMPOL computation must reproduce the
legacy compute route exactly on the committed 12.4.1 fixture.

``chmpol_cases.json`` was generated by ``generate_compute_route_cases.py``
in the old virtualenv at the pinned commit: the five legacy cleaners, then
the legacy ``score_indicator`` with the route's formula. Legacy CHMPOL has no
impute route. The Rotterdam dataset holds Stockholm data on purpose
(CHMPOL-1 in docs/methodology-conflicts.md).
"""

import json

import pytest

from sspi.imputation import is_imputed
from sspi.indicators import compute_indicator, registry
from sspi.ingestion.runner import fetch_and_normalize, resolve_datasets
from sspi.metadata import MetadataCatalog
from tests.golden.parity import INDICATOR_CASES, assert_parity, load_cases, score_records, source_fixtures

CASES = load_cases(INDICATOR_CASES["CHMPOL"])


class _RowsClient:
    def __init__(self, rows):
        self.rows = rows

    def fetch_indicator(self, code):
        return self.rows


@pytest.fixture(scope="module")
def observations():
    catalog = MetadataCatalog.load()
    (fixture_path,) = source_fixtures(CASES)
    rows = json.loads(fixture_path.read_text())["data"]
    results, _ = fetch_and_normalize(resolve_datasets(list(registry.get("CHMPOL").dataset_codes), catalog), _RowsClient(rows), metadata=catalog)
    return [o for _, result in results for o in result.observations]


@pytest.fixture(scope="module")
def result(observations):
    return compute_indicator(registry.get("CHMPOL"), observations, recipients=())


def test_golden_file_records_the_legacy_facts():
    assert CASES["indicator_code"] == "CHMPOL" and CASES["impute_route_exists"] is False and CASES["goalposts"] is None
    assert "/ 5 / 100" in CASES["formula"]


def test_scores_match_the_legacy_compute_route(result):
    assert_parity("CHMPOL scores", score_records(result.observed_scores, imputation=False), CASES["scores"])
    assert len(result.observed_scores) == 8


def test_classification_and_missingness_match_legacy(result, observations):
    assert result.imputed_scores == () and not any(is_imputed(s) for s in result.scores)
    assert sorted({(u.country_code, u.year) for u in result.unscored}) == [tuple(i) for i in CASES["incomplete_identities"]]
    identities = {(o.country_code, o.year) for o in observations}
    assert identities == {(s.country_code, s.year) for s in result.scores} | {(u.country_code, u.year) for u in result.unscored}
