"""Parity for ISHRAT against the legacy compute route on the committed WID
fixture: identities, scores, unit, inputs, incomplete groups.

``ishrat_cases.json`` was generated by ``generate_inequality_cases.py`` in the
old virtualenv at the pinned commit, running the legacy WID cleaners and the
``compute_ishrat`` view function itself. Legacy ISHRAT has no impute route.
"""

import pytest

from sspi.imputation import is_imputed
from sspi.indicators import compute_indicator, registry
from sspi.indicators.ishrat import UNIT
from sspi.metadata import CountryCatalog
from tests.golden.inequality import wid_observations
from tests.golden.parity import INDICATOR_CASES, assert_parity, load_cases, score_records

CASES = load_cases(INDICATOR_CASES["ISHRAT"])


@pytest.fixture(scope="module")
def result():
    return compute_indicator(registry.get("ISHRAT"), wid_observations())


def test_golden_file_records_the_legacy_facts():
    definition = registry.get("ISHRAT")
    assert CASES["indicator_code"] == "ISHRAT" and CASES["impute_route_exists"] is False and not definition.imputes
    assert CASES["goalposts"] == [0.2, 1.25] == list(definition.goalposts)
    assert CASES["unit"] == UNIT == definition.unit == "Ratio of Bottom 50% Income Share to to Top 10% Income Share"
    assert CASES["formula"] == "goalpost(WID_NINCSH_PRETAX_P0P50 / WID_NINCSH_PRETAX_P90P100, 0.2, 1.25)"
    assert definition.dataset_codes == ("WID_NINCSH_PRETAX_P90P100", "WID_NINCSH_PRETAX_P0P50") and definition.score_dependencies == ()


def test_scores_match_the_compute_route_exactly(result):
    assert_parity("ISHRAT scores", score_records(result.observed_scores, imputation=False), CASES["scores"])
    assert len(result.observed_scores) == 1650


def test_nothing_is_imputed_and_nothing_is_incomplete(result):
    assert result.imputed_scores == () and not any(is_imputed(s) for s in result.scores)
    assert [[u.country_code, u.year] for u in result.unscored] == CASES["incomplete_identities"] == []


def test_coverage_is_the_sspi67_members_for_2000_to_2024(result):
    assert {s.country_code for s in result.scores} == set(CountryCatalog.load().group("SSPI67").members)
    assert {s.year for s in result.scores} == set(range(2000, 2025))


def test_score_is_computed_from_the_float32_inputs(result):
    """MYS 2024: published shares 0.1921 and 0.3653; the legacy inputs are their float32 representations, and the
    score is computed from those, not from the published decimals."""
    score = next(s for s in result.scores if (s.country_code, s.year) == ("MYS", 2024))
    inputs = {o.dataset_code: o.value for o in score.inputs}
    assert inputs == {"WID_NINCSH_PRETAX_P0P50": 0.1921000034, "WID_NINCSH_PRETAX_P90P100": 0.3652999997}
    assert score.score == (0.1921000034 / 0.3652999997 - 0.2) / (1.25 - 0.2)
    assert score.score != (0.1921 / 0.3653 - 0.2) / (1.25 - 0.2)
