"""Parity for UIS_YRSEDU and YRSEDU against the legacy cleaner and BOTH
legacy routes on the committed UIS response: observations (including the
zeros the legacy cleaner drops), observed scores (compute route), imputed
scores (impute route: backward extrapolation of the input only), units,
input snapshots, identities and classification.

``uis_yrsedu_cases.json`` and ``yrsedu_cases.json`` were generated by
``generate_education_cases.py`` in the old virtualenv at the pinned commit,
running the registered legacy cleaner and the ``compute_yrsedu`` /
``impute_yrsedu`` view functions themselves. Every comparison is exact; no
tolerance.
"""

import json
from collections import Counter
from functools import cache
from pathlib import Path

import pytest

from sspi.imputation import is_imputed
from sspi.indicators import compute_indicator, registry, yrsedu
from sspi.indicators.strategy import SeriesFillThenScore
from sspi.ingestion.runner import SUPPORTED_DATASETS, fetch_and_normalize, resolve_datasets
from sspi.ingestion.uis import UISIndicatorData
from sspi.metadata import MetadataCatalog
from tests.golden.parity import (
    INDICATOR_CASES,
    INTENTIONAL_DIVERGENCES,
    OBSERVATION_CASES,
    OBSERVATION_IDENTITY,
    PENDING_METHODOLOGY_DECISIONS,
    assert_parity,
    legacy_inconsistency,
    load_cases,
    observation_record,
    score_level_records,
)

UIS_DIRECTORY = Path(__file__).parents[1] / "fixtures" / "uis"
CATALOG = MetadataCatalog.load()
RELEASE = json.loads((UIS_DIRECTORY / "versions_default.json").read_text())["version"]
SERIES = "YEARS.FC.COMP.1T3"


@cache
def records():
    return json.loads((UIS_DIRECTORY / f"{SERIES}_sample.json").read_text(encoding="utf-8"))["records"]


class FixtureClient:
    def __init__(self):
        self.fetches = []

    def fetch_indicator(self, indicator):
        self.fetches.append(indicator)
        return UISIndicatorData(indicator, RELEASE, tuple(records()))


@cache
def normalized():
    client = FixtureClient()
    ((dataset, result),), _ = fetch_and_normalize(resolve_datasets(["UIS_YRSEDU"], CATALOG), client, metadata=CATALOG)
    assert dataset.code == "UIS_YRSEDU" and client.fetches == [SERIES]
    return result


@cache
def run():
    return compute_indicator(registry.get("YRSEDU"), normalized().observations)


@pytest.fixture(scope="module")
def dataset_case():
    return load_cases(OBSERVATION_CASES["UIS_YRSEDU"])


@pytest.fixture(scope="module")
def indicator_case():
    return load_cases(INDICATOR_CASES["YRSEDU"])


def scores():
    return {(s.country_code, s.year): s for s in run().scores}


# --- UIS_YRSEDU ---------------------------------------------------------------------------------


def test_dataset_is_the_uis_years_of_compulsory_education_through_the_shared_adapter(dataset_case):
    source = CATALOG.dataset("UIS_YRSEDU").source
    assert dataset_case["source_indicator"] == SERIES == source.query_code == source.organization_series_code and source.organization_code == "UIS"
    assert "UIS_YRSEDU" in SUPPORTED_DATASETS and dataset_case["source_version"] == RELEASE
    assert dataset_case["descriptions"] == ["Number of years of compulsory primary and secondary education guaranteed in legal frameworks"]
    assert {r["indicatorId"] for r in records()} == {SERIES} and CATALOG.dataset("UIS_YRSEDU").unit == "Years"


def test_observations_match_the_legacy_cleaner_exactly(dataset_case):
    result = normalized()
    assert_parity("UIS_YRSEDU observations", [observation_record(o) for o in result.observations], dataset_case["observations"], OBSERVATION_IDENTITY)
    assert len(result.observations) == 336 and {o.unit for o in result.observations} == {"Years"} and {o.provenance["source_version"] for o in result.observations} == {RELEASE}
    assert {o.value for o in result.observations} == {5.0, 6.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0}  # whole years; 0 never survives


def test_the_legacy_cleaner_drops_every_zero_although_uis_marks_it_nil(dataset_case):
    result = normalized()
    zeros = [r for r in records() if r["value"] == 0]
    assert len(zeros) == 52 == result.missing_values == dataset_case["empty_source_values"]  # every "missing" value here is a reported 0
    assert {r["magnitude"] for r in zeros} == {"NIL"} and {r["magnitude"] for r in records() if r["value"] != 0} == {None}
    assert not any(r["value"] is None for r in records()) and dataset_case["skipped_areas"] == [] == list(result.skipped_areas)
    assert len(records()) == 336 + 52


# --- YRSEDU -------------------------------------------------------------------------------------


def test_golden_file_records_the_legacy_facts(indicator_case):
    definition = registry.get("YRSEDU")
    definition.check_against(CATALOG)
    assert indicator_case["formula"] == "goalpost(UIS_YRSEDU, 6, 12)" == indicator_case["methodology_score_function"].removeprefix("Score = ")
    assert indicator_case["goalposts"] == [6, 12] == list(definition.goalposts)
    assert indicator_case["unit"] == indicator_case["imputed_unit"] == "Years" == definition.unit == yrsedu.UNIT
    assert indicator_case["series_fill"] == {"backward_to": 2000, "forward_to": None, "interpolation": None}
    assert definition.imputation == SeriesFillThenScore(yrsedu.score_yrsedu, (2000, 2023), steps=("backward",))
    assert definition.dataset_codes == ("UIS_YRSEDU",) and definition.score_dependencies == () and definition.auxiliary_datasets == () and definition.recipient_group is None


def test_legacy_output_is_consistent_so_exact_parity_is_required(indicator_case):
    assert legacy_inconsistency(indicator_case) is None
    assert indicator_case["legacy_output_conflicts"] == {"observed_and_imputed": [], "duplicate_imputed": []}
    assert not any(code == "YRSEDU" for code, _ in list(INTENTIONAL_DIVERGENCES) + list(PENDING_METHODOLOGY_DECISIONS))


def test_observed_scores_match_the_compute_route(indicator_case):
    result = run()
    assert_parity("YRSEDU observed scores", score_level_records(result.observed_scores), indicator_case["observed_scores"])
    assert len(result.observed_scores) == 336 and not any(is_imputed(s) for s in result.observed_scores)


def test_imputed_scores_match_the_impute_route(indicator_case):
    result = run()
    assert_parity("YRSEDU imputed scores", score_level_records(result.imputed_scores), indicator_case["imputed_scores"])
    assert len(result.imputed_scores) == 37 and all(is_imputed(s) for s in result.imputed_scores)
    assert {s.inputs[0].provenance["imputation_method"] for s in result.imputed_scores} == {"Backward Extrapolation"}  # nothing forward, nothing interpolated
    assert {s.unit for s in result.scores} == {"Years"}


def test_final_identity_set_classification_and_provenance(indicator_case):
    result = run()
    legacy = {(r["country_code"], r["year"]) for key in ("observed_scores", "imputed_scores") for r in indicator_case[key]}
    identities = [(s.country_code, s.year) for s in result.scores]
    assert len(identities) == len(set(identities)) == 373 and set(identities) == legacy and result.unscored == ()
    assert all(s.provenance == {} for s in result.scores)
    for s in result.imputed_scores:
        (source,) = s.inputs
        assert source.provenance["imputed"] is True and s.score == yrsedu.score_yrsedu(source.value)


def test_six_years_or_fewer_score_zero_twelve_or_more_score_one():
    assert yrsedu.score_yrsedu(6) == 0.0 and yrsedu.score_yrsedu(4) == 0.0 and yrsedu.score_yrsedu(9) == 0.5 and yrsedu.score_yrsedu(12) == 1.0 == yrsedu.score_yrsedu(13)
    s = scores()
    assert s[("AUT", 2023)].score == s[("USA", 2023)].score == 1.0 and s[("MYS", 2023)].score == 0.0  # 12, 12 and 6 years
    assert s[("DEU", 2023)].inputs[0].value == 13.0 and s[("DEU", 2023)].score == 1.0


def test_yrsedu_1_a_reported_zero_takes_the_first_later_value_through_backward_extrapolation():
    s = scores()
    # (country, last year UIS reports 0, first later value, its score): the legacy result for every year 2000..last zero
    for country, last_zero, value, score in (("MYS", 2002, 6.0, 0.0), ("IDN", 2001, 9.0, 0.5), ("IND", 2008, 8.0, 1 / 3), ("NGA", 2003, 9.0, 0.5), ("OMN", 2014, 10.0, 2 / 3)):
        assert yrsedu.score_yrsedu(value) == pytest.approx(score) and yrsedu.score_yrsedu(0) == 0.0  # what the source's 0 would have scored
        for year in range(2000, last_zero + 1):
            row = s[(country, year)]
            assert is_imputed(row) and row.inputs[0].value == value and row.score == yrsedu.score_yrsedu(value)
            assert row.inputs[0].provenance["imputation_method"] == "Backward Extrapolation" and row.inputs[0].provenance["anchor_year"] == last_zero + 1
        assert (country, 1999) not in s  # 1998-1999 zeros: before the 2000 target, so no score at all
    assert sorted(y for c, y in s if c == "SHN") == [1998]  # one value, then zeros: nothing after 1998, nothing carried forward
    assert {y for c, y in s if c == "ALB"} & {2018, 2019, 2020} == set()  # an interior gap is not interpolated
    assert Counter(c for c, y in s if 2000 <= y <= 2023 and c in ("MYS", "AUT", "USA", "IND")) == {"MYS": 24, "AUT": 24, "USA": 24, "IND": 24}
