"""Differential test: the new CountryCatalog must reproduce exactly what the
legacy country-group builders produced from ``local/country-groups.json``:
group order, member order, per-country group order and pycountry names.

`country_cases.json` was generated by `generate_country_cases.py` in the old
virtualenv (see `generated_from.commit`). No edits were applied; the fixture
is the legacy output verbatim. The test needs only the JSON.
"""

import json
from pathlib import Path

import pytest

from sspi.metadata import CountryCatalog

FIXTURE = Path(__file__).with_name("country_cases.json")
PAYLOAD = json.loads(FIXTURE.read_text(encoding="utf-8"))


@pytest.fixture(scope="module")
def catalog():
    return CountryCatalog.load()


def test_fixture_records_its_provenance():
    meta = PAYLOAD["generated_from"]
    assert meta["repository"] == "sspi-data-webapp"
    assert meta["source_file"] == "local/country-groups.json"
    assert len(meta["commit"]) == 40
    assert meta["working_tree_dirty"] is False


def test_groups_match_legacy_exactly_including_order(catalog):
    assert [(g.code, list(g.members)) for g in catalog.groups()] == [(g["code"], g["members"]) for g in PAYLOAD["groups"]]


@pytest.mark.parametrize("expected", PAYLOAD["groups"], ids=[g["code"] for g in PAYLOAD["groups"]])
def test_group_lookup_matches_legacy_country_group(catalog, expected):
    assert list(catalog.group(expected["code"]).members) == expected["members"]


def test_country_universe_matches_legacy_country_details(catalog):
    assert [c.code for c in catalog.countries()] == [c["code"] for c in PAYLOAD["countries"]]


@pytest.mark.parametrize("expected", PAYLOAD["countries"], ids=[c["code"] for c in PAYLOAD["countries"]])
def test_country_detail_matches_legacy(catalog, expected):
    country = catalog.country(expected["code"])
    assert country.name == expected["name"]
    assert list(country.groups) == expected["groups"]
    assert list(catalog.groups_for(expected["code"])) == expected["groups"]
