"""Differential test: the new metadata catalog must reproduce the semantic
values the OLD loader produced from the legacy methodology and dataset files.

`metadata_cases.json` was generated by `generate_metadata_cases.py` against
the old file-walking loader (see `generated_from.commit`). The documented
migration edits from PROVENANCE.yaml were applied while generating, so the
fixture holds expected values, not known legacy inconsistencies. The test
needs only the JSON.
"""

import json
from pathlib import Path

import pytest

from sspi.metadata import DatasetMetadata, MetadataCatalog, UnresolvedDataset

FIXTURE = Path(__file__).with_name("metadata_cases.json")
PAYLOAD = json.loads(FIXTURE.read_text())


@pytest.fixture(scope="module")
def catalog():
    return MetadataCatalog.load()


def test_fixture_records_its_provenance():
    meta = PAYLOAD["generated_from"]
    assert meta["repository"] == "sspi-data-webapp"
    assert len(meta["commit"]) == 40
    assert meta["working_tree_dirty"] is False


def test_same_indicator_and_dataset_universe(catalog):
    assert {i.code for i in catalog.indicators()} == {i["code"] for i in PAYLOAD["indicators"]}
    assert {d.code for d in catalog.datasets()} == {d["code"] for d in PAYLOAD["datasets"]}
    assert {u.code for u in catalog.unresolved_datasets()} == {u["code"] for u in PAYLOAD["unresolved_datasets"]}


@pytest.mark.parametrize("expected", PAYLOAD["indicators"], ids=[i["code"] for i in PAYLOAD["indicators"]])
def test_indicator_matches_old_loader(catalog, expected):
    indicator = catalog.indicator(expected["code"])
    assert indicator.name == expected["name"]
    assert indicator.pillar_code == expected["pillar_code"]
    assert indicator.category_code == expected["category_code"]
    assert list(indicator.dataset_codes) == expected["dataset_codes"]
    assert indicator.lower_goalpost == expected["lower_goalpost"]
    assert indicator.upper_goalpost == expected["upper_goalpost"]
    assert [d.code for d in catalog.dataset_dependencies(expected["code"])] == expected["dataset_codes"]


@pytest.mark.parametrize("expected", PAYLOAD["datasets"], ids=[d["code"] for d in PAYLOAD["datasets"]])
def test_dataset_matches_old_loader(catalog, expected):
    dataset = catalog.dataset(expected["code"])
    assert isinstance(dataset, DatasetMetadata)
    assert dataset.name == expected["name"]
    assert dataset.dataset_type == expected["dataset_type"]
    assert dataset.unit == expected["unit"]
    assert dataset.source.organization_code == expected["source"]["organization_code"]
    assert dataset.source.query_code == expected["source"]["query_code"]
    assert dataset.source.organization_series_code == expected["source"]["organization_series_code"]


@pytest.mark.parametrize("expected", PAYLOAD["unresolved_datasets"], ids=[u["code"] for u in PAYLOAD["unresolved_datasets"]])
def test_unresolved_dataset_is_explicit(catalog, expected):
    dataset = catalog.dataset(expected["code"])
    assert isinstance(dataset, UnresolvedDataset)
    assert [i.code for i in catalog.indicators_using(expected["code"])] == expected["referenced_by"]
