"""Parity for TF_CRPTAX and CRPTAX against the legacy collector, cleaner and
BOTH legacy routes on a verbatim subset of the approved Tax Foundation file
(January 2025 edition): observations, observed scores (compute route),
imputed scores (impute route: backward extrapolation to 2000, then
interpolation, on the input), units, identities and classification.

``tf_crptax_cases.json`` and ``crptax_cases.json`` were generated by
``generate_tax_cases.py crptax`` in the old virtualenv at the pinned commit,
running the legacy collector (its HTTP answer served from the fixture), the
registered cleaner and the ``compute_crptax`` / ``impute_crptax`` view
functions themselves. Every comparison is exact; no tolerance. The 2018
static values are evidence for CRPTAX-1 only, never the expected result.
"""

import hashlib
from collections import Counter
from functools import cache
from pathlib import Path

import pytest

from sspi.imputation import is_imputed
from sspi.indicators import compute_indicator, crptax, registry
from sspi.indicators.strategy import SeriesFillThenScore
from sspi.ingestion.runner import SUPPORTED_DATASETS, fetch_and_normalize, resolve_datasets
from sspi.ingestion.taxfoundation import FILES, TaxFoundationFile
from sspi.metadata import MetadataCatalog
from tests.golden.parity import (
    INDICATOR_CASES,
    INTENTIONAL_DIVERGENCES,
    OBSERVATION_CASES,
    OBSERVATION_IDENTITY,
    PENDING_METHODOLOGY_DECISIONS,
    assert_parity,
    legacy_inconsistency,
    load_cases,
    observation_record,
    score_level_records,
)

FIXTURE = Path(__file__).parents[1] / "fixtures" / "taxfoundation" / "rates_final_2025-01_sample.csv"
CATALOG = MetadataCatalog.load()
KEY = "rates_final_2025-01"


class FixtureClient:
    """Stands in for ``TaxFoundationClient``; counts fetches."""

    def __init__(self):
        self.fetches = []

    def fetch_file(self, key):
        self.fetches.append(key)
        content = FIXTURE.read_bytes()
        return TaxFoundationFile(key, FILES[key], hashlib.sha256(content).hexdigest(), content.decode("utf-8"))


@cache
def normalized():
    client = FixtureClient()
    ((dataset, result),), _ = fetch_and_normalize(resolve_datasets(["TF_CRPTAX"], CATALOG), client, metadata=CATALOG)
    assert dataset.code == "TF_CRPTAX" and client.fetches == [KEY]
    return result


@cache
def run():
    return compute_indicator(registry.get("CRPTAX"), normalized().observations)


def scores():
    return {(s.country_code, s.year): s for s in run().scores}


@pytest.fixture(scope="module")
def dataset_case():
    return load_cases(OBSERVATION_CASES["TF_CRPTAX"])


@pytest.fixture(scope="module")
def indicator_case():
    return load_cases(INDICATOR_CASES["CRPTAX"])


# --- TF_CRPTAX ----------------------------------------------------------------------------------


def test_dataset_is_the_approved_2025_01_edition_the_legacy_collector_read(dataset_case):
    source = CATALOG.dataset("TF_CRPTAX").source
    assert dataset_case["source_url"] == FILES[KEY].url == "https://taxfoundation.org/wp-content/uploads/2025/01/rates_final.csv"
    assert dataset_case["legacy_source_info"] == {"OrganizationName": "Tax Foundation", "OrganizationCode": "TF", "QueryCode": "rates_final", "URL": FILES[KEY].url}
    assert source.organization_code == "TF" and source.query_code == KEY and FILES[KEY].edition == "2025/01" and "TF_CRPTAX" in SUPPORTED_DATASETS
    assert dataset_case["descriptions"] == ["Corporate Taxes"] and CATALOG.dataset("TF_CRPTAX").unit == "Tax Rate" == {o["unit"] for o in dataset_case["observations"]}.pop()


def test_fixture_is_a_verbatim_subset_of_the_approved_file():
    lines = FIXTURE.read_bytes().split(b"\r\n")
    assert lines[0].startswith(b'"","iso_2","iso_3","continent","country","1980"') and lines[0].endswith(b'"2024"') and lines[-1] == b""
    assert len(lines) - 2 == 21  # header, 21 rows, trailing CRLF


def test_observations_match_the_legacy_cleaner_exactly(dataset_case):
    result = normalized()
    assert_parity("TF_CRPTAX observations", [observation_record(o) for o in result.observations], dataset_case["observations"], OBSERVATION_IDENTITY)
    assert len(result.observations) == 731 and result.missing_values == dataset_case["empty_source_values"] == 214 and result.skipped_areas == ()
    assert {o.provenance["source_edition"] for o in result.observations} == {"2025/01"} and {o.provenance["source_url"] for o in result.observations} == {FILES[KEY].url}


def test_country_and_year_coverage_match_legacy(dataset_case):
    result = normalized()
    areas = {o.country_code for o in result.observations}
    assert len(areas) == 20 and {"ANT", "XKX"} <= areas and "PRK" not in areas  # no ISO filter; an all-NA area has no row
    assert (min(o.year for o in result.observations), max(o.year for o in result.observations)) == (1980, 2024) == tuple(dataset_case["source_years"])


def test_reported_zero_rates_are_kept():
    result = normalized()
    zeros = [o for o in result.observations if o.value == 0]
    assert {o.country_code for o in zeros} == {"ARE", "BHR", "JEY"} and len([o for o in zeros if o.country_code == "BHR"]) == 45


# --- CRPTAX -------------------------------------------------------------------------------------


def test_golden_file_records_the_legacy_facts(indicator_case):
    definition = registry.get("CRPTAX")
    definition.check_against(CATALOG)
    assert indicator_case["formula"] == "goalpost(TF_CRPTAX, 0, 40)" == indicator_case["methodology_score_function"].removeprefix("Score = ")
    assert indicator_case["goalposts"] == [0, 40] == list(definition.goalposts)
    assert indicator_case["unit"] == indicator_case["imputed_unit"] == "Tax Rate" == definition.unit == crptax.UNIT
    assert indicator_case["series_fill"] == {"backward_to": 2000, "forward_to": None, "interpolation": "every interior gap, any year"}
    assert definition.imputation == SeriesFillThenScore(crptax.score_crptax, (2000, 2023), steps=("backward", "interpolate"))
    assert definition.dataset_codes == ("TF_CRPTAX",) and definition.score_dependencies == () and definition.auxiliary_datasets == () and definition.recipient_group is None


def test_legacy_output_is_consistent_so_exact_parity_is_required(indicator_case):
    assert legacy_inconsistency(indicator_case) is None
    assert indicator_case["legacy_output_conflicts"] == {"observed_and_imputed": [], "duplicate_imputed": []}
    assert not any(code == "CRPTAX" for code, _ in list(INTENTIONAL_DIVERGENCES) + list(PENDING_METHODOLOGY_DECISIONS))


def test_observed_scores_match_the_compute_route(indicator_case):
    result = run()
    assert_parity("CRPTAX observed scores", score_level_records(result.observed_scores), indicator_case["observed_scores"])
    assert len(result.observed_scores) == 731 and not any(is_imputed(s) for s in result.observed_scores)


def test_imputed_scores_match_the_impute_route(indicator_case):
    result = run()
    assert_parity("CRPTAX imputed scores", score_level_records(result.imputed_scores), indicator_case["imputed_scores"])
    assert len(result.imputed_scores) == 69 and all(is_imputed(s) for s in result.imputed_scores)
    assert Counter(s.inputs[0].provenance["imputation_method"] for s in result.imputed_scores) == {"Backward Extrapolation": 49, "Linear Interpolation": 20}
    assert {s.unit for s in result.scores} == {"Tax Rate"}


def test_final_identity_set_classification_and_provenance(indicator_case):
    result = run()
    legacy = {(r["country_code"], r["year"]) for key in ("observed_scores", "imputed_scores") for r in indicator_case[key]}
    identities = [(s.country_code, s.year) for s in result.scores]
    assert len(identities) == len(set(identities)) == 800 and set(identities) == legacy and result.unscored == ()
    assert all(s.provenance == {} for s in result.scores)  # imputation is on the input, never on the score
    for s in result.imputed_scores:
        (source,) = s.inputs
        assert source.provenance["imputed"] is True and s.score == crptax.score_crptax(source.value)


def test_series_fill_cases():
    s = scores()
    # late starters are carried back to 2000 from their first year
    for country, first, value in (("NIU", 2020, 30.0), ("COM", 2015, 35.0), ("XKX", 2014, 10.0)):
        assert all(s[(country, y)].inputs[0].provenance["anchor_year"] == first and s[(country, y)].inputs[0].value == value for y in range(2000, first))
        assert (country, 1999) not in s and not is_imputed(s[(country, first)])
    # interior gaps are interpolated, also before 2000
    assert s[("ZAF", 1995)].inputs[0].provenance["imputation_method"] == "Linear Interpolation" and s[("ZAF", 1995)].score == 1.0
    assert s[("KWT", 1999)].inputs[0].value == 55.0 and s[("ANT", 2000)].inputs[0].provenance["imputation_method"] == "Linear Interpolation"
    # no forward extrapolation: the Netherlands Antilles stop in 2009
    assert max(y for c, y in s if c == "ANT") == 2009 and not any(is_imputed(x) for x in run().scores if x.year > 2020)
    # early observations are scored as published, all years from 1980; an all-NA area has no score
    assert not is_imputed(s[("USA", 1980)]) and not any(c == "PRK" for c, _ in s)


def test_higher_rate_higher_score_on_zero_to_forty():
    s = scores()
    assert s[("BHR", 2010)].score == 0.0 and s[("ARE", 2022)].score == 0.0 and s[("ARE", 2023)].score == 0.225  # 0 % then 9 %
    assert s[("SGP", 1980)].score == 1.0 and s[("IRN", 1991)].inputs[0].value == 75.0 and s[("IRN", 1991)].score == 1.0  # 40 % and above
    assert (s[("MYS", 2023)].score, s[("AUT", 2023)].score, s[("USA", 2023)].score) == (0.6, 0.6, 25.768 / 40)


def test_crptax_1_the_combined_rate_is_scored_not_the_2018_static_central_rate():
    """The 2018 static SSPI used 15 % for Germany and Canada, 8.5 % for Switzerland, 21 % for the United States and
    23.2 % for Japan; the executable source has the combined statutory rate. The source value is the expected result."""
    s = scores()
    combined = {"DEU": 29.825, "CAN": 26.8, "CHE": 21.148581, "USA": 25.83858, "JPN": 29.74}
    static = {"DEU": 15.0, "CAN": 15.0, "CHE": 8.5, "USA": 21.0, "JPN": 23.2}
    for country, rate in combined.items():
        assert s[(country, 2018)].inputs[0].value == rate and s[(country, 2018)].score == rate / 40 != static[country] / 40


def test_an_empty_dataset_scores_nothing_as_in_legacy(indicator_case):
    assert indicator_case["empty_dataset"] == {"observed_scores": [], "imputed_scores": [], "legacy_impute_error": None}
    empty = compute_indicator(registry.get("CRPTAX"), ())
    assert empty.scores == () and empty.unscored == ()
