"""Parity for COALPW against BOTH legacy routes on the committed
``TESbySource`` rows, the ALTNRG fixture: COALPW reads the same seven
canonical datasets, whose own parity is in ``test_golden_altnrg.py``.

``coalpw_cases.json`` was generated by ``generate_ghg_cases.py`` in the old
virtualenv at the pinned commit, running the seven registered cleaners and
the ``compute_coalpw`` / ``impute_coalpw`` view functions themselves. Every
comparison is exact; no tolerance.
"""

from collections import Counter

import pytest

from sspi.imputation import is_imputed
from sspi.indicators import coalpw, compute_indicator, registry
from sspi.indicators.strategy import ConstantFillInputsThenScore
from sspi.metadata import CountryCatalog, MetadataCatalog
from sspi.scoring import score_indicator
from tests.golden.energy import ALTNRG_DATASETS, altnrg_observations
from tests.golden.parity import INDICATOR_CASES, INTENTIONAL_DIVERGENCES, PENDING_METHODOLOGY_DECISIONS, RESOLVED_METHODOLOGY_DECISIONS, assert_parity, legacy_inconsistency, load_cases, score_level_records

SSPI67 = tuple(CountryCatalog.load().group("SSPI67").members)
GOLDEN = load_cases(INDICATOR_CASES["COALPW"])
DEFINITION = registry.get("COALPW")
FIXTURE_COUNTRIES = {"AUT", "BOL", "JPN", "LTU", "MYS", "PAK", "SGP", "USA"}


def incomplete(groups):
    return sorted(({"country_code": u.country_code, "year": u.year, "datasets": sorted(o.dataset_code for o in u.inputs)} for u in groups), key=lambda r: (r["country_code"], r["year"]))


@pytest.fixture(scope="module")
def result():
    return compute_indicator(DEFINITION, altnrg_observations(), SSPI67)


def test_golden_file_records_the_legacy_facts():
    DEFINITION.check_against(MetadataCatalog.load())
    assert GOLDEN["indicator_code"] == "COALPW" and tuple(GOLDEN["dataset_codes"]) == ALTNRG_DATASETS == DEFINITION.dataset_codes == registry.get("ALTNRG").dataset_codes
    assert GOLDEN["goalposts"] == [0.4, 0] == list(DEFINITION.goalposts) and GOLDEN["unit"] == "Index" == DEFINITION.unit
    assert GOLDEN["methodology_score_function"] == MetadataCatalog.load().indicator("COALPW").score_function
    strategy, imputation = DEFINITION.imputation, GOLDEN["imputation"]
    assert isinstance(strategy, ConstantFillInputsThenScore) and strategy.formula is coalpw.score_coalpw_imputed
    assert (imputation["backward_to"], imputation["forward_to"]) == strategy.years == tuple(imputation["zero_fill"]["years"]) == (2000, 2023)
    assert (imputation["zero_fill"]["recipient_group"], imputation["zero_fill"]["unit"], imputation["zero_total_score"]) == (strategy.recipient_group, strategy.fill_unit, coalpw.ZERO_TOTAL_SCORE) == ("SSPI67", "PJ", 1.0)
    assert DEFINITION.computed_series == () and DEFINITION.score_dependencies == () and DEFINITION.auxiliary_datasets == ()


def test_legacy_output_is_consistent_so_exact_parity_is_required():
    assert legacy_inconsistency(GOLDEN) is None and GOLDEN["legacy_output_conflicts"] == {"observed_and_imputed": [], "duplicate_imputed": []}
    registered = list(INTENTIONAL_DIVERGENCES) + list(PENDING_METHODOLOGY_DECISIONS) + list(RESOLVED_METHODOLOGY_DECISIONS)
    assert not any(code == "COALPW" for code, _ in registered)


def test_observed_scores_match_the_compute_route(result):
    assert_parity("COALPW observed scores", score_level_records(result.observed_scores), GOLDEN["observed_scores"])
    assert len(result.observed_scores) == 91 and not any(is_imputed(s) for s in result.observed_scores)
    for score in result.observed_scores:
        values = {o.dataset_code: o.value for o in score.inputs}
        total = values["IEA_TLCOAL"] + values["IEA_NATGAS"] + values["IEA_NCLEAR"] + values["IEA_HYDROP"] + values["IEA_GEOPWR"] + values["IEA_BIOWAS"] + values["IEA_FSLOIL"]
        assert score.score == coalpw.score_coalpw_observed(**values) == max(0.0, min(1.0, (values["IEA_TLCOAL"] / total - 0.4) / (0 - 0.4)))  # a fraction, not a percentage
        assert score.computed == ()  # no stored share: the legacy route computes none
    assert Counter(s.country_code for s in result.observed_scores) == {"USA": 36, "JPN": 35, "PAK": 12, "LTU": 8}  # the same groups ALTNRG scores


def test_incomplete_observed_groups_match_the_compute_route():
    observed = score_indicator(altnrg_observations(), "COALPW", DEFINITION.observed_score, DEFINITION.unit)
    assert incomplete(observed.unscored) == GOLDEN["observed_incomplete"] and len(observed.unscored) == 193


def test_imputed_scores_match_the_impute_route(result):
    assert_parity("COALPW imputed scores", score_level_records(result.imputed_scores), GOLDEN["imputed_scores"])
    assert len(result.imputed_scores) == 1518 and all(is_imputed(s) for s in result.imputed_scores)
    assert all(s.computed == () and s.provenance == {} and len(s.inputs) == 7 for s in result.imputed_scores)
    methods = Counter(o.provenance["imputation_method"] for s in result.imputed_scores for o in s.inputs if o.provenance.get("imputed"))
    assert methods == {"Zero imputation for missing energy type": 10008, "Backward Extrapolation": 24, "Forward Extrapolation": 14, "Linear Interpolation": 8}


def test_final_identity_set_and_incomplete_identities_are_those_of_altnrg(result):
    legacy = {(r["country_code"], r["year"]) for key in ("observed_scores", "imputed_scores") for r in GOLDEN[key]}
    identities = [(s.country_code, s.year) for s in result.scores]
    assert len(identities) == len(set(identities)) == 91 + 1518 and set(identities) == legacy
    assert incomplete(result.unscored) == GOLDEN["incomplete_after_imputation"] and len(result.unscored) == 91
    altnrg = compute_indicator(registry.get("ALTNRG"), altnrg_observations(), SSPI67)
    assert {(s.country_code, s.year) for s in altnrg.scores} == set(identities)  # same inputs, same impute shape: same identities, different scores


def test_zero_total_scores_one_where_altnrg_scores_zero(result):
    """COALPW-1: a member absent from every dataset has a zero-filled total for 2000-2023. COALPW scores it 1.0 (the
    legacy "perfect score"), ALTNRG 0.0. In this fixture that is every SSPI67 member the sample does not include."""
    scores = {(s.country_code, s.year): s for s in result.scores}
    absent = sorted(set(SSPI67) - FIXTURE_COUNTRIES)
    assert len(absent) == 59
    for country in absent:
        for year in (2000, 2023):
            score = scores[(country, year)]
            assert score.score == 1.0 and is_imputed(score) and {o.value for o in score.inputs} == {0.0} and {o.unit for o in score.inputs} == {"PJ"}
    assert coalpw.score_coalpw_imputed(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0) == 1.0
    with pytest.raises(ZeroDivisionError):
        coalpw.score_coalpw_observed(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0)  # the compute route has no guard; the cleaner never lets a zero through


def test_behaviour_on_the_committed_rows(result):
    scores = {(s.country_code, s.year): s for s in result.scores}
    usa = scores[("USA", 2022)]
    assert not is_imputed(usa) and 0 < usa.score < 1
    for country in ("MYS", "AUT"):  # no nuclear row: every 2000-2023 score rests on a zero-filled nuclear input
        series = [scores[(country, year)] for year in range(2000, 2024)]
        assert all(is_imputed(s) and next(o for o in s.inputs if o.dataset_code == "IEA_NCLEAR").value == 0.0 for s in series)
    assert not any(s.country_code == "BOL" for s in result.scores)  # not a member and no nuclear row: never scored
    assert (min(y for _, y in scores), max(y for _, y in scores)) == (1990, 2025)
