"""Parity for WB_TAXREV and TAXREV against the legacy cleaner and BOTH legacy
routes on the committed World Bank response sample: observations, observed
scores (compute route), imputed scores (impute route: series fill on the
input, then the hard-coded Vietnam/Nigeria/Venezuela/Algeria reference
class), units, identities and classification.

``wb_taxrev_cases.json`` and ``taxrev_cases.json`` were generated by
``generate_tax_cases.py`` in the old virtualenv at the pinned commit,
running the registered legacy cleaner and the ``compute_taxrev`` /
``impute_taxrev`` view functions themselves. Every comparison is exact; no
tolerance.
"""

import json
from collections import Counter
from functools import cache
from pathlib import Path

import pytest

from sspi.errors import ImputationError
from sspi.imputation import REFERENCE_CLASS_AVERAGE, is_imputed
from sspi.indicators import compute_indicator, registry, taxrev
from sspi.indicators.strategy import SeriesFillThenScore
from sspi.ingestion.runner import SUPPORTED_DATASETS, fetch_and_normalize, resolve_datasets
from sspi.metadata import CountryCatalog, MetadataCatalog
from sspi.scoring import Observation
from tests.golden.parity import (
    INDICATOR_CASES,
    INTENTIONAL_DIVERGENCES,
    OBSERVATION_CASES,
    OBSERVATION_IDENTITY,
    PENDING_METHODOLOGY_DECISIONS,
    assert_parity,
    legacy_inconsistency,
    load_cases,
    observation_record,
    score_level_records,
)

FIXTURE = Path(__file__).parents[1] / "fixtures" / "wb" / "GC.TAX.TOTL.GD.ZS_sample.json"
CATALOG = MetadataCatalog.load()
SKIPPED = {"EUU", "WLD", "XD", "XKX"}  # two aggregates with an ISO3 code, one without (High income, id XD), Kosovo
RECIPIENTS = ("VNM", "NGA", "VEN", "DZA")


@cache
def rows():
    return json.loads(FIXTURE.read_text(encoding="utf-8"))[1]


class FixtureClient:
    """Stands in for ``WorldBankClient``; counts fetches."""

    def __init__(self):
        self.fetches = []

    def fetch_indicator(self, indicator):
        self.fetches.append(indicator)
        return rows()


@cache
def normalized():
    client = FixtureClient()
    ((dataset, result),), _ = fetch_and_normalize(resolve_datasets(["WB_TAXREV"], CATALOG), client, metadata=CATALOG)
    assert dataset.code == "WB_TAXREV" and client.fetches == ["GC.TAX.TOTL.GD.ZS"]
    return result


@cache
def run():
    return compute_indicator(registry.get("TAXREV"), normalized().observations)


def scores():
    return {(s.country_code, s.year): s for s in run().scores}


@pytest.fixture(scope="module")
def dataset_case():
    return load_cases(OBSERVATION_CASES["WB_TAXREV"])


@pytest.fixture(scope="module")
def indicator_case():
    return load_cases(INDICATOR_CASES["TAXREV"])


# --- WB_TAXREV ----------------------------------------------------------------------------------


def test_dataset_is_the_wdi_central_government_tax_revenue_share_of_gdp(dataset_case):
    source = CATALOG.dataset("WB_TAXREV").source
    assert dataset_case["source_indicator"] == "GC.TAX.TOTL.GD.ZS" == source.query_code == source.organization_series_code
    assert source.organization_code == "WB" and "WB_TAXREV" in SUPPORTED_DATASETS
    assert dataset_case["descriptions"] == ["Tax revenue (% of GDP)"]
    assert CATALOG.dataset("WB_TAXREV").unit == "% of GDP" == {o["unit"] for o in dataset_case["observations"]}.pop()  # the cleaner's literal (PROVENANCE)


def test_observations_match_the_legacy_cleaner_exactly(dataset_case):
    result = normalized()
    assert_parity("WB_TAXREV observations", [observation_record(o) for o in result.observations], dataset_case["observations"], OBSERVATION_IDENTITY)
    assert len(result.observations) == 339 and {o.provenance["description"] for o in result.observations} == {"Tax revenue (% of GDP)"}


def test_skipped_areas_missing_values_and_coverage_match_legacy(dataset_case):
    result = normalized()
    assert [list(s) for s in result.skipped_areas] == dataset_case["skipped_areas"] and {code for code, _ in result.skipped_areas} == SKIPPED
    assert result.missing_values == dataset_case["empty_source_values"] == 783
    assert not any(r["value"] == 0 for r in rows()) and not any(r["value"] is not None and r["value"] < 0 for r in rows())  # no zero, no negative
    countries = {o.country_code for o in result.observations}
    assert len(countries) == 12 and not countries & {"PAK", *RECIPIENTS}  # every row of these five is null
    assert (min(o.year for o in result.observations), max(o.year for o in result.observations)) == (1972, 2024)  # no country or year filter
    assert max(o.value for o in result.observations) == 638.661722364669  # SDN 1999: kept as published, a share of GDP above 100


# --- TAXREV -------------------------------------------------------------------------------------


def test_golden_file_records_the_legacy_facts(indicator_case):
    definition = registry.get("TAXREV")
    definition.check_against(CATALOG)
    assert indicator_case["formula"] == "goalpost(WB_TAXREV, 0, 50)" and indicator_case["methodology_score_function"] == "Score = goalpost(WB_TAXREV, 0, 50)"
    assert indicator_case["goalposts"] == [0, 50] == list(definition.goalposts)
    assert indicator_case["unit"] == indicator_case["imputed_unit"] == "Percentage" == definition.unit == taxrev.UNIT
    assert indicator_case["impute_route_exists"] is True and definition.imputes
    assert definition.imputation == SeriesFillThenScore(taxrev.score_taxrev, (2000, 2023), listed_recipients=RECIPIENTS)
    assert indicator_case["series_fill"] == {"forward_to": 2023, "backward_to": 2000, "interpolation": "every interior gap, any year"}
    assert definition.dataset_codes == ("WB_TAXREV",) and definition.score_dependencies == () and definition.auxiliary_datasets == ()
    assert definition.recipient_group is None  # the recipients are a hard-coded list, not a group


def test_legacy_output_is_consistent_so_exact_parity_is_required(indicator_case):
    assert legacy_inconsistency(indicator_case) is None
    assert indicator_case["legacy_output_conflicts"] == {"observed_and_imputed": [], "duplicate_imputed": []}
    assert not any(code == "TAXREV" for code, _ in list(INTENTIONAL_DIVERGENCES) + list(PENDING_METHODOLOGY_DECISIONS))


def test_observed_scores_match_the_compute_route(indicator_case):
    result = run()
    assert_parity("TAXREV observed scores", score_level_records(result.observed_scores), indicator_case["observed_scores"])
    assert len(result.observed_scores) == 339 and not any(is_imputed(s) for s in result.observed_scores)


def test_imputed_scores_match_the_impute_route(indicator_case):
    result = run()
    assert_parity("TAXREV imputed scores", score_level_records(result.imputed_scores), indicator_case["imputed_scores"])
    assert len(result.imputed_scores) == 235 and all(is_imputed(s) for s in result.imputed_scores)
    assert {s.unit for s in result.scores} == {"Percentage"}


def test_final_identity_set_classification_and_provenance(indicator_case):
    result = run()
    legacy = {(r["country_code"], r["year"]) for key in ("observed_scores", "imputed_scores") for r in indicator_case[key]}
    identities = [(s.country_code, s.year) for s in result.scores]
    assert len(identities) == len(set(identities)) == 574 and set(identities) == legacy and result.unscored == ()
    assert all(s.provenance == {} for s in result.scores)  # imputation is on the input, never on the score
    for s in result.imputed_scores:
        (source,) = s.inputs
        assert source.provenance["imputed"] is True and s.score == taxrev.score_taxrev(source.value)


def test_higher_revenue_is_better_on_zero_to_fifty():
    assert taxrev.score_taxrev(0) == 0.0 and taxrev.score_taxrev(25) == 0.5 and taxrev.score_taxrev(50) == 1.0
    s = scores()
    assert s[("ARE", 2016)].inputs[0].value == 0.040683437400096 and s[("ARE", 2016)].score == 0.040683437400096 / 50  # the smallest share
    assert s[("TLS", 2012)].score == 1.0 == s[("SDN", 1999)].score  # 147.6% and 638.7% of GDP: clamped by the goalpost only
    assert s[("AUT", 2023)].score > s[("MYS", 2023)].score > s[("USA", 2023)].score  # 25.6, 12.6 and 10.6 percent of GDP


def test_series_fill_behaviour():
    result = run()
    by_method = Counter(s.inputs[0].provenance["imputation_method"] for s in result.imputed_scores)
    assert by_method == {REFERENCE_CLASS_AVERAGE: 96, "Forward Extrapolation": 78, "Linear Interpolation": 33, "Backward Extrapolation": 28}
    s = scores()
    # TAXREV-3: Japan's series ends in 1993 and is carried forward thirty years
    japan = s[("JPN", 2023)].inputs[0].provenance
    assert (japan["imputation_method"], japan["anchor_year"], japan["imputation_distance"]) == ("Forward Extrapolation", 1993, 30)
    assert s[("JPN", 2023)].inputs[0].value == 11.1445521483154
    assert s[("IND", 2020)].inputs[0].provenance["imputation_method"] == "Linear Interpolation"  # 2019-2021 interior gap
    assert s[("AND", 2000)].inputs[0].provenance["anchor_year"] == 2018  # backward from the first value
    # interpolation is not bounded by the 2000-2023 window (Kuwait 1975-1976); nothing is carried past 2023
    assert min(x.year for x in result.imputed_scores) == 1975 and max(x.year for x in result.imputed_scores) == 2023
    assert max(x.year for x in result.observed_scores) == 2024  # no year filter on observed scores


def test_taxrev_1_reference_class_is_the_flat_mean_of_every_row_for_the_four_listed_countries(indicator_case):
    observations = normalized().observations
    mean = sum(o.value for o in observations) / len(observations)  # every country, every year from 1972, unweighted, outliers included
    reference = indicator_case["reference_class"]
    assert (reference["recipients"], reference["years"], reference["reference_count"], reference["mean"]) == (list(RECIPIENTS), [2000, 2023], 339, mean)
    for country in RECIPIENTS:
        theirs = [s for s in run().scores if s.country_code == country]
        assert {s.year for s in theirs} == set(range(2000, 2024)) and all(is_imputed(s) for s in theirs)
        assert {(s.inputs[0].value, s.inputs[0].provenance["reference_observation_count"]) for s in theirs} == {(mean, 339)}
        assert {s.score for s in theirs} == {taxrev.score_taxrev(mean)}
    # TAXREV-2: Pakistan, an SSPI67 member with no value either, is not on the list and gets nothing
    assert "PAK" in CountryCatalog.load().group("SSPI67").members and not any(c == "PAK" for c, _ in scores())


def test_a_listed_recipient_with_observed_rows_raises_before_scoring():
    nigeria = Observation("WB_TAXREV", "NGA", 2015, 5.0, "% of GDP", {})
    with pytest.raises(ImputationError, match=r"\['NGA'\] now have observed WB_TAXREV rows"):
        compute_indicator(registry.get("TAXREV"), (*normalized().observations, nigeria))


def test_an_empty_dataset_raises_as_the_legacy_impute_route_did(indicator_case):
    assert indicator_case["empty_dataset"] == {"observed_scores": [], "legacy_impute_error": "ValueError: Reference data cannot be empty."}
    with pytest.raises(ImputationError, match="reference data for WB_TAXREV/VNM is empty"):
        compute_indicator(registry.get("TAXREV"), ())
