"""Parity for the two WID post-tax income-share datasets and TXRDST against
the legacy cleaners and the legacy compute route on the committed WID
fixture: observations (legacy float32 values), identities, scores, unit,
inputs, incomplete groups, and the legacy score function itself on inputs
the fixture does not hold (zero shares, goalpost boundaries).

``wid_nincsh_posttax_equalsplit_*_cases.json`` and ``txrdst_cases.json``
were generated by ``generate_tax_cases.py`` in the old virtualenv at the
pinned commit, running the registered legacy WID cleaners and the
``compute_txrdst`` view function. Legacy TXRDST has no impute route. Every
comparison is exact; no tolerance.
"""

import logging

import pytest

from sspi.imputation import is_imputed
from sspi.indicators import compute_indicator, registry, txrdst
from sspi.ingestion.runner import SUPPORTED_DATASETS, fetch_and_normalize, resolve_datasets
from sspi.ingestion.wid import LEGACY_COUNTRY_GROUP, LEGACY_YEARS, series_selection
from sspi.metadata import CountryCatalog, MetadataCatalog
from tests.golden.inequality import FixtureClients, normalized
from tests.golden.parity import INDICATOR_CASES, OBSERVATION_CASES, OBSERVATION_IDENTITY, assert_parity, load_cases, observation_record, score_records, source_fixtures

CATALOG = MetadataCatalog.load()
POSTTAX = ("WID_NINCSH_POSTTAX_EQUALSPLIT_P0P50", "WID_NINCSH_POSTTAX_EQUALSPLIT_P90P100")
PRETAX = ("WID_NINCSH_PRETAX_P0P50", "WID_NINCSH_PRETAX_P90P100")
DATASETS = POSTTAX + PRETAX  # the legacy score function's parameter order
CASES = load_cases(INDICATOR_CASES["TXRDST"])


def observations(removed=frozenset()):
    results = normalized(DATASETS)
    return tuple(o for code in DATASETS for o in results[code].observations if (o.dataset_code, o.country_code, o.year) not in removed)


@pytest.fixture(scope="module")
def result():
    return compute_indicator(registry.get("TXRDST"), observations())


# --- post-tax WID datasets ----------------------------------------------------------------------


@pytest.fixture(scope="module", params=POSTTAX)
def posttax(request):
    code = request.param
    return code, load_cases(OBSERVATION_CASES[code]), normalized(DATASETS)[code]


def test_posttax_golden_file_describes_this_dataset(posttax):
    code, case, _ = posttax
    selection = series_selection(CATALOG.dataset(code))
    assert case["dataset_code"] == code and code in SUPPORTED_DATASETS
    assert case["source_selection"] == {"archive": "wid_all_data", "variable": "sdiincj992", "percentile": selection.percentile, "years": list(LEGACY_YEARS), "country_group": LEGACY_COUNTRY_GROUP}
    assert (selection.archive, selection.variable) == ("wid_all_data", "sdiincj992") and selection.percentile == code.rsplit("_", 1)[1].lower()
    assert [p.name for p in source_fixtures(case)] == ["wid"]


def test_posttax_observations_match_the_legacy_cleaner_exactly(posttax):
    code, case, result_ = posttax
    assert_parity(f"{code} observations", [observation_record(o) for o in result_.observations], case["observations"], OBSERVATION_IDENTITY)
    assert len(result_.observations) == 1650 and result_.skipped_areas == () and result_.missing_values == 0
    assert {o.unit for o in result_.observations} == {CATALOG.dataset(code).unit.strip()} == {f"share; percentile {code.rsplit('_', 1)[1].lower()}; sdiincj992"}
    assert {o.country_code for o in result_.observations} == set(CountryCatalog.load().group("SSPI67").members)
    assert {o.year for o in result_.observations} == set(range(2000, 2025))  # 1998, 1999 and p99p100 are in the fixture and are not kept


def test_posttax_values_are_the_legacy_float32_representation(posttax):
    code, case, result_ = posttax
    published = {(p["country_code"], p["year"]): p["published"] for p in case["published_values"]}
    assert all(o.provenance["source_value"] == published[(o.country_code, o.year)] for o in result_.observations)
    assert sum(1 for o in result_.observations if o.value != float(o.provenance["source_value"])) > 1600


def test_all_four_shares_come_from_one_archive_fetch():
    clients = FixtureClients()
    _, fetches = fetch_and_normalize(resolve_datasets(list(DATASETS), CATALOG), clients, metadata=CATALOG)
    assert fetches == ("wid_all_data",) and clients.fetches == [("WID", "wid_all_data")]


# --- TXRDST -------------------------------------------------------------------------------------


def test_golden_file_records_the_legacy_facts():
    definition = registry.get("TXRDST")
    definition.check_against(CATALOG)
    assert CASES["indicator_code"] == "TXRDST" and CASES["impute_route_exists"] is False and not definition.imputes
    assert CASES["goalposts"] == [-10, 100] == list(definition.goalposts)
    assert CASES["formula"] == "goalpost((posttax_ratio - pretax_ratio) / pretax_ratio * 100, -10, 100)"
    assert CASES["methodology_score_function"].endswith("* 100, -10, -100)")  # TXRDST-1: the prose says -100, the executable reads 100
    assert CASES["unit"] == txrdst.UNIT == definition.unit == "Ratio of Bottom 50% Income Share to to Top 10% Income Share"
    assert CASES["score_function_parameters"] == list(DATASETS) == list(definition.dataset_codes)
    assert definition.score_dependencies == () and definition.auxiliary_datasets == ()  # the shares themselves; never ISHRAT or GINIPT scores


def test_scores_match_the_compute_route_exactly(result):
    assert_parity("TXRDST scores", score_records(result.observed_scores, imputation=False), CASES["scores"])
    assert len(result.observed_scores) == 1650 and {s.unit for s in result.scores} == {txrdst.UNIT}


def test_nothing_is_imputed_and_nothing_is_incomplete(result):
    assert result.imputed_scores == () and not any(is_imputed(s) for s in result.scores) and all(s.provenance == {} for s in result.scores)
    assert [[u.country_code, u.year] for u in result.unscored] == CASES["incomplete_identities"] == []
    assert {s.country_code for s in result.scores} == set(CountryCatalog.load().group("SSPI67").members) and {s.year for s in result.scores} == set(range(2000, 2025))


def test_a_group_missing_any_share_is_unscored_as_in_legacy():
    (variant,) = CASES["variants"]
    removed = frozenset(tuple(r) for r in variant["removed_observations"])
    partial = compute_indicator(registry.get("TXRDST"), observations(removed))
    assert variant["name"] == "with_rows_removed" and len(removed) == 5
    assert_parity("TXRDST scores, rows removed", score_records(partial.observed_scores, imputation=False), variant["scores"])
    assert sorted([u.country_code, u.year] for u in partial.unscored) == variant["incomplete_identities"] == [["AUT", 2000], ["AUT", 2001], ["MYS", 2005], ["USA", 2024]]
    assert partial.imputed_scores == () and len(partial.observed_scores) == 1646


def test_score_is_the_percentage_change_of_the_float32_share_ratio(result):
    """MYS 2023: the bottom-50%/top-10% ratio rises from 0.526 before tax to 0.611 after: +16.2%, scored on -10..100."""
    score = next(s for s in result.scores if (s.country_code, s.year) == ("MYS", 2023))
    v = {o.dataset_code: o.value for o in score.inputs}
    assert v == {"WID_NINCSH_POSTTAX_EQUALSPLIT_P0P50": 0.2073999941, "WID_NINCSH_POSTTAX_EQUALSPLIT_P90P100": 0.3395999968, "WID_NINCSH_PRETAX_P0P50": 0.1921000034, "WID_NINCSH_PRETAX_P90P100": 0.3652999997}
    pretax = v["WID_NINCSH_PRETAX_P0P50"] / v["WID_NINCSH_PRETAX_P90P100"]
    posttax = v["WID_NINCSH_POSTTAX_EQUALSPLIT_P0P50"] / v["WID_NINCSH_POSTTAX_EQUALSPLIT_P90P100"]
    assert score.score == ((posttax - pretax) / pretax * 100 - -10) / (100 - -10) == 0.23759148586025589
    by_identity = {(s.country_code, s.year): s.score for s in result.scores}
    assert by_identity[("USA", 2023)] > by_identity[("AUT", 2023)] > by_identity[("MYS", 2023)]


@pytest.mark.parametrize("case", CASES["score_function_cases"], ids=lambda c: c["case"])
def test_the_score_function_matches_the_legacy_closure_on_edge_inputs(case, caplog):
    if case["error"] is not None:
        with pytest.raises(ZeroDivisionError):
            txrdst.score_txrdst(**case["inputs"])
        assert case["error"] == "ZeroDivisionError"
        return
    with caplog.at_level(logging.WARNING, logger="sspi.indicators.txrdst"):
        assert txrdst.score_txrdst(**case["inputs"]) == case["score"]
    assert [r.getMessage() for r in caplog.records] == case["warnings"]


def test_edge_case_outcomes_are_the_documented_legacy_behavior():
    outcome = {c["case"]: (c["score"], c["error"]) for c in CASES["score_function_cases"]}
    assert outcome["no redistribution"] == (10 / 110, None) == outcome["zero pre-tax bottom share"]  # a zero pre-tax ratio scores as no change
    assert outcome["ratio exactly doubles"] == (1.0, None) == outcome["ratio more than doubles"]
    assert outcome["ratio falls by more than 10%"] == (0.0, None) == outcome["zero post-tax bottom share"]
    assert outcome["zero post-tax top share"] == (None, "ZeroDivisionError") == outcome["zero pre-tax top share"]
