"""Parity for DEFRST against BOTH legacy routes on the committed FAO Land Use
bulk-file sample: observed scores (compute route, level rows from 2000),
score-level imputed scores (impute route: forward extrapolation of scores,
reference-class mean of scores for BEL/ARE/LUX), identities, classification.

``defrst_cases.json`` was generated by ``generate_fao_land_cases.py`` in the
old virtualenv at the pinned commit, running the legacy cleaners, the legacy
``score_indicator`` and the legacy ``impute_defrst`` view function itself.
Two variants: ``without_are_source_rows``, the source state the route's
hard-coded recipient list was written against, on which exact parity is
required; and ``fixture_as_committed``, current source data on which the
legacy route stores an observed and an imputed score for the same ARE
country-years (and two imputed scores for ARE 2023). That variant is a
resolved methodology decision (``RESOLVED_METHODOLOGY_DECISIONS``, DEFRST-1,
direction B: impute only when observed data is unavailable): the expected
result is the legacy output with ARE's reference-class rows removed, held
exactly.
"""

import pytest

from sspi.imputation import is_imputed
from sspi.indicators import IndicatorDefinition, compute_indicator, registry
from sspi.indicators.defrst import REFERENCE_CLASS_RECIPIENTS, keep_for_scoring, score_defrst
from sspi.ingestion.fao import read_bulk_csv
from sspi.ingestion.runner import fetch_and_normalize, resolve_datasets
from sspi.metadata import MetadataCatalog
from tests.golden.parity import INDICATOR_CASES, INTENTIONAL_DIVERGENCES, PENDING_METHODOLOGY_DECISIONS, RESOLVED_METHODOLOGY_DECISIONS, assert_parity, legacy_inconsistency, load_cases, score_level_records, source_fixtures

CASES = load_cases(INDICATOR_CASES["DEFRST"])
VARIANTS = {v["name"]: v for v in CASES["variants"]}
PARITY_VARIANT = "without_are_source_rows"


class _BulkClient:
    def __init__(self, rows):
        self.rows = rows

    def fetch_domain(self, domain):
        return self.rows


def observations_for(variant_name):
    catalog = MetadataCatalog.load()
    (path,) = source_fixtures(CASES)
    rows = read_bulk_csv(path.read_text(encoding="utf-8"), "RL")
    if variant_name == PARITY_VARIANT:
        rows = [r for r in rows if r["Area"] != "United Arab Emirates"]  # the generator dropped ARE's ISO3 rows after adaptation; same rows
    results, _ = fetch_and_normalize(resolve_datasets(["UNFAO_FRSTLV", "UNFAO_FRSTAV"], catalog), _BulkClient(rows), metadata=catalog)
    return tuple(o for _, r in results for o in r.observations)


def test_golden_file_records_the_legacy_facts():
    assert CASES["indicator_code"] == "DEFRST" and CASES["impute_route_exists"] is True
    assert CASES["goalposts"] == [-20.0, 40.0] == list(registry.get("DEFRST").goalposts)
    assert CASES["level_year_filter"] == ">= 2000"
    assert tuple(CASES["reference_class_recipients"]) == REFERENCE_CLASS_RECIPIENTS
    assert registry.get("DEFRST").auxiliary_datasets == () and registry.get("DEFRST").recipient_group is None


def test_current_source_case_is_resolved_by_imputing_only_without_observed_data():
    """ARE has naturally-regenerating-forest rows now. The legacy impute route still gives it reference-class scores for
    2000-2023, so its output holds an observed and an imputed score for ARE 2000-2022 and two imputed scores for ARE 2023.
    DEFRST-1 was resolved for direction B (2026-10-08): a listed country with observed scores is not a recipient. The
    expected result is the legacy output with ARE's reference-class rows removed: ARE keeps its observed scores and its
    forward-extrapolated 2023, BEL and LUX keep the legacy reference-class score, every other row is unchanged."""
    variant = VARIANTS["fixture_as_committed"]
    assert variant["legacy_impute_error"] is None  # the legacy route does not raise, it stores conflicting rows
    conflicts = variant["legacy_output_conflicts"]
    assert conflicts["observed_and_imputed"] == [["ARE", y] for y in range(2000, 2023)] and conflicts["duplicate_imputed"] == [["ARE", 2023]]
    assert legacy_inconsistency(variant) and RESOLVED_METHODOLOGY_DECISIONS[("DEFRST", "fixture_as_committed")] == "DEFRST-1"
    assert ("DEFRST", "fixture_as_committed") not in INTENTIONAL_DIVERGENCES and ("DEFRST", "fixture_as_committed") not in PENDING_METHODOLOGY_DECISIONS

    run = compute_indicator(registry.get("DEFRST"), observations_for("fixture_as_committed"))
    expected_imputed = [r for r in variant["imputed_scores"] if not (r["country_code"] == "ARE" and r["imputation_method"] == "ImputeReferenceClassAverage")]
    assert len(variant["imputed_scores"]) - len(expected_imputed) == 24  # exactly ARE's 2000-2023 reference-class rows are dropped
    assert_parity("DEFRST observed scores (current source)", score_level_records(run.observed_scores), variant["scores"])
    assert_parity("DEFRST imputed scores (current source, DEFRST-1 direction B)", score_level_records(run.imputed_scores), expected_imputed)
    assert len(run.observed_scores) == 207 and len(run.imputed_scores) == 57

    are = {s.year: s for s in run.scores if s.country_code == "ARE"}
    assert sorted(are) == list(range(2000, 2024)) and not any(is_imputed(are[y]) for y in range(2000, 2023))
    assert are[2023].provenance["imputation_method"] == "Forward Extrapolation" and are[2023].score == are[2022].score
    reference = [s for s in run.imputed_scores if s.provenance["imputation_method"] == "ImputeReferenceClassAverage"]
    assert {s.country_code for s in reference} == {"BEL", "LUX"} and len(reference) == 48
    assert all(s.provenance["reference_score_count"] == 184 for s in reference)  # the reference class is unchanged: listed countries never contribute

    identities = [(s.country_code, s.year) for s in run.scores]
    assert len(identities) == len(set(identities))
    legacy_incomplete = {tuple(i) for i in variant["incomplete_identities"]}
    assert {(u.country_code, u.year) for u in run.unscored} == legacy_incomplete - {(s.country_code, s.year) for s in run.imputed_scores}


@pytest.fixture(scope="module")
def result():
    return compute_indicator(registry.get("DEFRST"), observations_for(PARITY_VARIANT))


def test_parity_variant_is_consistent_legacy_output():
    assert legacy_inconsistency(VARIANTS[PARITY_VARIANT]) is None


def test_observed_scores_match_the_compute_route(result):
    variant = VARIANTS[PARITY_VARIANT]
    assert_parity("DEFRST observed scores", score_level_records(result.observed_scores), variant["scores"])
    assert len(result.observed_scores) == 184
    assert not any(is_imputed(s) for s in result.observed_scores)
    assert max(s.year for s in result.observed_scores) == 2022  # the forest average stops at 2022 (DEFRST-2)
    assert min(s.year for s in result.observed_scores) == 2000  # level rows before 2000 never score


def test_incomplete_identities_match_the_compute_route(result):
    """The compute route's incomplete groups, minus the identities the impute route filled (the 2023 extrapolations
    and the recipients' 2000-2023), are what is still unscored after imputation."""
    variant = VARIANTS[PARITY_VARIANT]
    legacy_incomplete = {tuple(i) for i in variant["incomplete_identities"]}
    filled = {(s.country_code, s.year) for s in result.imputed_scores}
    assert {(u.country_code, u.year) for u in result.unscored} == legacy_incomplete - filled
    assert {(u.country_code, u.year) for u in result.unscored}.isdisjoint({(s.country_code, s.year) for s in result.scores})
    observed_only = compute_indicator(IndicatorDefinition("DEFRST", score_defrst, imputation=None, observation_filter=keep_for_scoring), observations_for(PARITY_VARIANT))
    assert {(u.country_code, u.year) for u in observed_only.unscored} == legacy_incomplete


def test_imputed_scores_match_the_impute_route(result):
    variant = VARIANTS[PARITY_VARIANT]
    assert_parity("DEFRST imputed scores", score_level_records(result.imputed_scores), variant["imputed_scores"])
    assert len(result.imputed_scores) == 80
    assert all(is_imputed(s) for s in result.imputed_scores)
    assert {(s.country_code, s.year) for s in result.observed_scores}.isdisjoint({(s.country_code, s.year) for s in result.imputed_scores})
    identities = [(s.country_code, s.year) for s in result.scores]
    assert len(identities) == len(set(identities))


def test_score_level_provenance_is_truthful(result):
    extrapolated = [s for s in result.imputed_scores if s.provenance["imputation_method"] == "Forward Extrapolation"]
    reference = [s for s in result.imputed_scores if s.provenance["imputation_method"] == "ImputeReferenceClassAverage"]
    assert len(extrapolated) == 8 and len(reference) == 72 and len(extrapolated) + len(reference) == len(result.imputed_scores)
    for s in extrapolated:
        assert s.year == 2023 and s.provenance["source_year"] == 2022 and s.provenance["imputation_distance"] == 1
        assert s.inputs and all(o.year == 2022 and not o.provenance.get("imputed") for o in s.inputs)  # the anchor year's inputs, no fabricated observation
        anchor = next(a for a in result.observed_scores if a.country_code == s.country_code and a.year == 2022)
        assert s.score == anchor.score
    assert {s.country_code for s in reference} == set(REFERENCE_CLASS_RECIPIENTS)
    for s in reference:
        assert s.inputs == () and s.provenance["reference_score_count"] == 184 and s.provenance["requested_years"] == [2000, 2023]
    assert {s.score for s in reference} == {sum(a.score for a in result.observed_scores) / 184}  # mean of every other country's observed score
