"""Parity for WB_PUPTCH and PUPTCH against the legacy cleaner and BOTH legacy
routes on the committed World Bank response sample: observations, observed
scores (compute route), imputed scores (impute route: series fill on the
input), units, identities and classification.

``wb_puptch_cases.json`` and ``puptch_cases.json`` were generated by
``generate_education_cases.py`` in the old virtualenv at the pinned commit,
running the registered legacy cleaner and the ``compute_puptch`` /
``impute_puptch`` view functions themselves. Every comparison is exact; no
tolerance.
"""

import json
from collections import Counter
from functools import cache
from pathlib import Path

import pytest

from sspi.imputation import is_imputed
from sspi.indicators import compute_indicator, puptch, registry
from sspi.indicators.strategy import SeriesFillThenScore
from sspi.ingestion.runner import SUPPORTED_DATASETS, fetch_and_normalize, resolve_datasets
from sspi.metadata import MetadataCatalog
from tests.golden.parity import (
    INDICATOR_CASES,
    INTENTIONAL_DIVERGENCES,
    OBSERVATION_CASES,
    OBSERVATION_IDENTITY,
    PENDING_METHODOLOGY_DECISIONS,
    assert_parity,
    legacy_inconsistency,
    load_cases,
    observation_record,
    score_level_records,
)

FIXTURE = Path(__file__).parents[1] / "fixtures" / "wb" / "SE.PRM.ENRL.TC.ZS_sample.json"
CATALOG = MetadataCatalog.load()
SKIPPED = {"AFE", "WLD", "XD", "XKX"}  # two aggregates with an ISO3 code, one without (High income, id XD), Kosovo


@cache
def rows():
    return json.loads(FIXTURE.read_text(encoding="utf-8"))[1]


class FixtureClient:
    """Stands in for ``WorldBankClient``; counts fetches."""

    def __init__(self):
        self.fetches = []

    def fetch_indicator(self, indicator):
        self.fetches.append(indicator)
        return rows()


@cache
def normalized():
    client = FixtureClient()
    ((dataset, result),), _ = fetch_and_normalize(resolve_datasets(["WB_PUPTCH"], CATALOG), client, metadata=CATALOG)
    assert dataset.code == "WB_PUPTCH" and client.fetches == ["SE.PRM.ENRL.TC.ZS"]
    return result


@cache
def run():
    return compute_indicator(registry.get("PUPTCH"), normalized().observations)


@pytest.fixture(scope="module")
def dataset_case():
    return load_cases(OBSERVATION_CASES["WB_PUPTCH"])


@pytest.fixture(scope="module")
def indicator_case():
    return load_cases(INDICATOR_CASES["PUPTCH"])


# --- WB_PUPTCH ----------------------------------------------------------------------------------


def test_dataset_is_the_wdi_primary_pupil_teacher_ratio_through_the_shared_adapter(dataset_case):
    source = CATALOG.dataset("WB_PUPTCH").source
    assert dataset_case["source_indicator"] == "SE.PRM.ENRL.TC.ZS" == source.query_code == source.organization_series_code
    assert source.organization_code == "WB" and "WB_PUPTCH" in SUPPORTED_DATASETS
    assert dataset_case["descriptions"] == ["Pupil-teacher ratio, primary"]  # all teachers, primary level; not trained or qualified teachers
    assert CATALOG.dataset("WB_PUPTCH").unit == "Average" == {o["unit"] for o in dataset_case["observations"]}.pop()  # the cleaner's literal (PROVENANCE)


def test_observations_match_the_legacy_cleaner_exactly(dataset_case):
    result = normalized()
    assert_parity("WB_PUPTCH observations", [observation_record(o) for o in result.observations], dataset_case["observations"], OBSERVATION_IDENTITY)
    assert len(result.observations) == 358 and {o.provenance["description"] for o in result.observations} == {"Pupil-teacher ratio, primary"}


def test_skipped_areas_missing_values_and_coverage_match_legacy(dataset_case):
    result = normalized()
    assert [list(s) for s in result.skipped_areas] == dataset_case["skipped_areas"] and {code for code, _ in result.skipped_areas} == SKIPPED
    assert result.missing_values == dataset_case["empty_source_values"] == 500
    valued = [r for r in rows() if r["value"] is not None]
    assert len(valued) == 456 and sum(1 for r in valued if (r["countryiso3code"] or r["country"]["id"]) in SKIPPED) == 456 - 358
    assert not any(r["value"] == 0 for r in rows())  # the source has no zero; the shared cleaner would drop one
    countries = {o.country_code for o in result.observations}
    assert len(countries) == 13 and (min(o.year for o in result.observations), max(o.year for o in result.observations)) == (1970, 2019)  # no country or year filter


# --- PUPTCH -------------------------------------------------------------------------------------


def test_golden_file_records_the_legacy_facts(indicator_case):
    definition = registry.get("PUPTCH")
    definition.check_against(CATALOG)
    assert indicator_case["formula"] == "goalpost(WB_PUPTCH, 40, 9)" and indicator_case["methodology_score_function"] == "Score = goalpost(WB_PUPTCH, 40, 9)"
    assert indicator_case["goalposts"] == [40, 9] == list(definition.goalposts)
    assert indicator_case["unit"] == indicator_case["imputed_unit"] == "Ratio" == definition.unit == puptch.UNIT
    assert indicator_case["impute_route_exists"] is True and definition.imputes
    assert definition.imputation == SeriesFillThenScore(puptch.score_puptch, (2000, 2023))
    assert (indicator_case["series_fill"]["backward_to"], indicator_case["series_fill"]["forward_to"]) == puptch.SERIES_FILL_YEARS
    assert definition.dataset_codes == ("WB_PUPTCH",) and definition.score_dependencies == () and definition.auxiliary_datasets == ()
    assert definition.recipient_group is None  # no reference class, no country group


def test_legacy_output_is_consistent_so_exact_parity_is_required(indicator_case):
    assert legacy_inconsistency(indicator_case) is None
    assert indicator_case["legacy_output_conflicts"] == {"observed_and_imputed": [], "duplicate_imputed": []}
    assert not any(code == "PUPTCH" for code, _ in list(INTENTIONAL_DIVERGENCES) + list(PENDING_METHODOLOGY_DECISIONS))


def test_observed_scores_match_the_compute_route(indicator_case):
    result = run()
    assert_parity("PUPTCH observed scores", score_level_records(result.observed_scores), indicator_case["observed_scores"])
    assert len(result.observed_scores) == 358 and not any(is_imputed(s) for s in result.observed_scores)


def test_imputed_scores_match_the_impute_route(indicator_case):
    result = run()
    assert_parity("PUPTCH imputed scores", score_level_records(result.imputed_scores), indicator_case["imputed_scores"])
    assert len(result.imputed_scores) == 231 and all(is_imputed(s) for s in result.imputed_scores)
    assert {s.unit for s in result.scores} == {"Ratio"}


def test_final_identity_set_classification_and_provenance(indicator_case):
    result = run()
    legacy = {(r["country_code"], r["year"]) for key in ("observed_scores", "imputed_scores") for r in indicator_case[key]}
    identities = [(s.country_code, s.year) for s in result.scores]
    assert len(identities) == len(set(identities)) == 589 and set(identities) == legacy and result.unscored == ()
    assert all(s.provenance == {} for s in result.scores)  # imputation is on the input, never on the score
    for s in result.imputed_scores:
        (source,) = s.inputs
        assert source.provenance["imputed"] is True and source.provenance["imputation_distance"] >= 1 and s.score == puptch.score_puptch(source.value)
    assert {s.country_code for s in result.imputed_scores} <= {s.country_code for s in result.observed_scores}


def test_lower_is_better_on_forty_to_nine():
    assert puptch.score_puptch(40) == 0.0 and puptch.score_puptch(9) == 1.0 and puptch.score_puptch(24.5) == 0.5
    scores = {(s.country_code, s.year): s for s in run().scores}
    assert scores[("CAF", 2008)].inputs[0].value == 100.23649 and scores[("CAF", 2008)].score == 0.0  # above 40: clamped by the goalpost only
    assert scores[("KWT", 2010)].inputs[0].value == 8.37512 and scores[("KWT", 2010)].score == 1.0
    assert scores[("AUT", 2017)].score > scores[("USA", 2017)].score  # 10.0 pupils per teacher beat 14.2


def test_series_fill_behaviour():
    result = run()
    by_method = Counter(s.inputs[0].provenance["imputation_method"] for s in result.imputed_scores)
    assert by_method == {"Forward Extrapolation": 125, "Linear Interpolation": 67, "Backward Extrapolation": 39}
    scores = {(s.country_code, s.year): s for s in result.scores}
    usa = {year for country, year in scores if country == "USA"}
    assert usa == set(range(2000, 2024)) and {y for y in usa if not is_imputed(scores[("USA", y)])} == {2014, 2015, 2017}
    assert scores[("USA", 2016)].inputs[0].provenance["imputation_method"] == "Linear Interpolation"
    assert scores[("USA", 2000)].inputs[0].provenance["anchor_year"] == 2014 and scores[("USA", 2023)].inputs[0].provenance["anchor_year"] == 2017
    # PUPTCH-1: forward extrapolation starts from the last observation however old
    venezuela = scores[("VEN", 2023)].inputs[0].provenance
    assert (venezuela["anchor_year"], venezuela["imputation_distance"]) == (1987, 36)
    assert scores[("AUS", 2023)].inputs[0].provenance["anchor_year"] == 1999
    # interpolation is not bounded by the 2000-2023 window; nothing is carried past 2023
    assert min(s.year for s in result.imputed_scores) == 1971 and max(s.year for s in result.imputed_scores) == 2023
    assert not is_imputed(scores[("KAZ", 2019)]) and max(s.year for s in result.observed_scores) == 2019  # no year filter on observed scores

