"""Parity for BEEFMK against BOTH legacy routes on the committed FAOSTAT Food
Balances and World Bank population rows: observed scores (compute route),
imputed scores (impute route: each country's scores carried back to 2000 and
forward to 2023, and the hard-coded recipient Singapore given the
reference-class mean of scores), identities and classification.

``beefmk_cases.json`` was generated by ``generate_ghg_cases.py`` in the old
virtualenv at the pinned commit, running the legacy cleaners and the
``compute_beefmk`` / ``impute_beefmk`` view functions themselves. Every
comparison is exact; no tolerance.
"""

from collections import Counter

import pytest

from sspi.errors import ImputationError
from sspi.imputation import is_imputed
from sspi.indicators import beefmk, compute_indicator, registry
from sspi.indicators.strategy import ExtrapolateScores
from sspi.metadata import CountryCatalog, MetadataCatalog
from sspi.scoring import Observation, score_indicator
from tests.golden.ghg import beefmk_observations
from tests.golden.parity import INDICATOR_CASES, INTENTIONAL_DIVERGENCES, PENDING_METHODOLOGY_DECISIONS, RESOLVED_METHODOLOGY_DECISIONS, assert_parity, legacy_inconsistency, load_cases, score_level_records

SSPI67 = tuple(CountryCatalog.load().group("SSPI67").members)
GOLDEN = load_cases(INDICATOR_CASES["BEEFMK"])
DEFINITION = registry.get("BEEFMK")


@pytest.fixture(scope="module")
def result():
    return compute_indicator(DEFINITION, beefmk_observations(), SSPI67)


def test_golden_file_records_the_legacy_facts():
    DEFINITION.check_against(MetadataCatalog.load())
    assert GOLDEN["indicator_code"] == "BEEFMK" and tuple(GOLDEN["dataset_codes"]) == DEFINITION.dataset_codes == ("UNFAO_BFPROD", "UNFAO_BFCONS", "WB_POPULN")
    assert GOLDEN["goalposts"] == [50, 0] == list(DEFINITION.goalposts) and GOLDEN["unit"] == "Index" == DEFINITION.unit
    assert GOLDEN["route_goalposts"] == {"production_per_capita": list(beefmk.PRODUCTION_GOALPOSTS), "consumption": list(beefmk.CONSUMPTION_GOALPOSTS)}
    assert "kilograms" in GOLDEN["methodology_description"] and "UN population" in GOLDEN["methodology_description"]  # BEEFMK-1
    strategy, extrapolation = DEFINITION.imputation, GOLDEN["score_extrapolation"]
    assert isinstance(strategy, ExtrapolateScores)
    assert (strategy.backward_to, strategy.forward_to) == (extrapolation["backward_to"], extrapolation["forward_to"]) == (2000, 2023)
    assert list(strategy.listed_recipients) == extrapolation["reference_class"]["listed_recipients"] == ["SGP"] and strategy.recipient_group is None
    assert list(strategy.reference_years) == extrapolation["reference_class"]["years"]


def test_legacy_output_is_consistent_so_exact_parity_is_required():
    assert legacy_inconsistency(GOLDEN) is None and GOLDEN["legacy_output_conflicts"] == {"observed_and_imputed": [], "duplicate_imputed": []}
    registered = list(INTENTIONAL_DIVERGENCES) + list(PENDING_METHODOLOGY_DECISIONS) + list(RESOLVED_METHODOLOGY_DECISIONS)
    assert not any(code == "BEEFMK" for code, _ in registered)


def test_observed_scores_match_the_compute_route(result):
    assert_parity("BEEFMK observed scores", score_level_records(result.observed_scores), GOLDEN["observed_scores"])
    assert len(result.observed_scores) == 114 and not any(is_imputed(s) for s in result.observed_scores)
    assert Counter(s.country_code for s in result.observed_scores) == {"AUT": 14, "BEL": 14, "CHN": 14, "KWT": 14, "LUX": 14, "MYS": 14, "USA": 14, "PAK": 11, "FSM": 5}
    assert (min(s.year for s in result.observed_scores), max(s.year for s in result.observed_scores)) == (2010, 2023)


def test_incomplete_observed_identities_match_the_compute_route():
    observed = score_indicator(beefmk_observations(), "BEEFMK", DEFINITION.observed_score, DEFINITION.unit)
    assert [[u.country_code, u.year] for u in sorted(observed.unscored, key=lambda u: (u.country_code, u.year))] == GOLDEN["observed_incomplete_identities"]


def test_imputed_scores_match_the_impute_route(result):
    assert_parity("BEEFMK imputed scores", score_level_records(result.imputed_scores), GOLDEN["imputed_scores"])
    assert len(result.imputed_scores) == 126 and all(is_imputed(s) for s in result.imputed_scores)
    methods = Counter(s.provenance["imputation_method"] for s in result.imputed_scores)
    assert methods == {"Backward Extrapolation": 99, "Forward Extrapolation": 3, "ImputeReferenceClassAverage": 24}
    identities = [(s.country_code, s.year) for s in result.scores]
    assert len(identities) == len(set(identities)) == 240


def test_singapore_gets_the_flat_mean_of_every_observed_score(result):
    singapore = [s for s in result.imputed_scores if s.country_code == "SGP"]
    mean = sum(s.score for s in result.observed_scores) / len(result.observed_scores)
    assert [s.year for s in singapore] == list(range(2000, 2024)) and {s.score for s in singapore} == {mean}
    assert all(s.inputs == () and s.provenance["reference_score_count"] == 114 for s in singapore)


def test_production_part_is_within_a_millionth_of_one(result):
    """BEEFMK-1: thousand tonnes divided by people is of the order of 1e-5, so goalpost(.., 50, 0) is 1.0 to six places
    and every score is at least one half."""
    for score in result.observed_scores:
        values = {o.dataset_code: o.value for o in score.inputs}
        production_part = max(0.0, min(1.0, (values["UNFAO_BFPROD"] / values["WB_POPULN"] - 50) / (0 - 50)))
        assert 1 - production_part < 1e-6
        assert score.score == (production_part + max(0.0, min(1.0, (values["UNFAO_BFCONS"] - 50) / (0 - 50)))) / 2
    assert min(s.score for s in result.scores) > 0.5


def test_a_listed_recipient_with_observed_scores_stops_the_run():
    """The legacy route would store an observed and an imputed score for Singapore; no precedence is decided."""
    singapore = (Observation("UNFAO_BFPROD", "SGP", 2015, 1.0, "1000 t"), Observation("UNFAO_BFCONS", "SGP", 2015, 10.0, "kg/capita/year"))  # population is already there
    with pytest.raises(ImputationError, match=r"\['SGP'\].*no precedence has been decided"):
        compute_indicator(DEFINITION, beefmk_observations() + singapore, SSPI67)
