"""Differential test: the orchestrated REDLST computation must reproduce the
legacy compute route exactly on the committed 15.5.1 fixture.

``redlst_cases.json`` was generated by ``generate_redlst_cases.py`` in the
old virtualenv at the pinned commit. Legacy REDLST has no impute route, so
the whole expected result is the compute route's output. The file records
the executable (0, 1) goalposts; the retired 2018 static data implies
(0.5, 1), a discrepancy preserved and not resolved here.
"""

import json
from pathlib import Path

import pytest

from sspi.indicators import compute_indicator, registry
from sspi.indicators.redlst import score_redlst
from sspi.ingestion.unsdg import normalize_unsdg_dataset
from sspi.metadata import MetadataCatalog

HERE = Path(__file__).parent
CASES = json.loads((HERE / "redlst_cases.json").read_text())


@pytest.fixture(scope="module")
def result():
    fixture = json.loads((HERE.parent.parent / CASES["generated_from"]["fixture"]).read_text())
    observations = normalize_unsdg_dataset(MetadataCatalog.load().dataset("UNSDG_REDLST"), fixture["data"]).observations
    return compute_indicator(registry.get("REDLST"), observations, recipients=())


def test_fixture_records_its_provenance():
    meta = CASES["generated_from"]
    assert meta["repository"] == "sspi-data-webapp" and meta["commit"] == "76f842b08e551dfa8fb9563e4c812be086654ba6"
    assert meta["working_tree_dirty"] is False
    assert CASES["impute_route_exists"] is False and "0.5" in CASES["historical_discrepancy"]


def test_goalposts_are_the_ones_the_legacy_route_read():
    definition = registry.get("REDLST")
    assert tuple(definition.goalposts) == (CASES["goalposts"]["lower"], CASES["goalposts"]["upper"]) == (0, 1)


@pytest.mark.parametrize("case", CASES["goalpost_cases"], ids=[str(c["value"]) for c in CASES["goalpost_cases"]])
def test_score_function_matches_legacy(case):
    assert score_redlst(case["value"]) == case["score"]


def test_scores_match_the_legacy_compute_route(result):
    new = [
        {"country_code": s.country_code, "year": s.year, "score": s.score, "unit": s.unit, "inputs": [{"dataset_code": o.dataset_code, "value": o.value, "unit": o.unit} for o in s.inputs]}
        for s in sorted(result.observed_scores, key=lambda s: (s.country_code, s.year))
    ]
    assert new == CASES["scores"] and len(new) == 230


def test_nothing_is_imputed_and_nothing_is_incomplete(result):
    assert result.imputed_scores == () and len(result.unscored) == CASES["incomplete_count"] == 0
