"""Parity for the seven IEA datasets and for ALTNRG against the legacy
cleaners and BOTH legacy routes, on the committed ``TESbySource`` rows.

``iea_*_cases.json`` and ``altnrg_cases.json`` were generated by
``generate_iea_cases.py`` in the old virtualenv at the pinned commit,
running the registered cleaners and the ``compute_altnrg`` /
``impute_altnrg`` view functions themselves. Every comparison is exact; no
tolerance.
"""

from collections import Counter

import pytest

from sspi.imputation import is_imputed
from sspi.indicators import altnrg, compute_indicator, registry
from sspi.metadata import CountryCatalog, MetadataCatalog
from sspi.scoring import score_indicator
from tests.golden.energy import ALTNRG_DATASETS, altnrg_observations, iea_normalized, iea_rows
from tests.golden.parity import (
    INDICATOR_CASES,
    INTENTIONAL_DIVERGENCES,
    OBSERVATION_CASES,
    OBSERVATION_IDENTITY,
    PENDING_METHODOLOGY_DECISIONS,
    assert_parity,
    legacy_inconsistency,
    load_cases,
    observation_record,
    score_level_records,
    summary,
)

SSPI67 = tuple(CountryCatalog.load().group("SSPI67").members)
GOLDEN = load_cases(INDICATOR_CASES["ALTNRG"])
DEFINITION = registry.get("ALTNRG")
# dataset -> (legacy product, the IEA's label for it, observations, null values, zero values) on the committed rows
EXPECTED = {
    "IEA_TLCOAL": ("COAL", "Coal and coal products", 258, 4, 0),
    "IEA_NATGAS": ("NATGAS", "Natural gas", 282, 0, 0),
    "IEA_NCLEAR": ("NUCLEAR", "Nuclear", 126, 0, 0),
    "IEA_HYDROP": ("HYDRO", "Hydropower", 249, 0, 0),
    "IEA_GEOPWR": ("GEOTHERM", "Solar, wind and other renewables", 201, 3, 7),
    "IEA_BIOWAS": ("COMRENEW", "Biofuels and waste", 284, 0, 0),
    "IEA_FSLOIL": ("MTOTOIL", "Oil and oil products", 284, 0, 0),
}
COUNTRIES = {"AUT", "BOL", "JPN", "LTU", "MYS", "PAK", "SGP", "USA"}


def records(scores):
    """Golden-file records: score, inputs with their imputation fields, the computed series, the score's own imputation fields."""
    ordered = sorted(scores, key=lambda s: (s.country_code, s.year))
    out = score_level_records(ordered)
    for record, score in zip(out, ordered):
        record["computed"] = [{"dataset_code": c.dataset_code, "value": c.value, "unit": c.unit} for c in score.computed]
    return [{key: record[key] for key in GOLDEN["observed_scores"][0]} for record in out]


def incomplete(groups):
    return sorted(({"country_code": u.country_code, "year": u.year, "datasets": sorted(o.dataset_code for o in u.inputs)} for u in groups), key=lambda r: (r["country_code"], r["year"]))


@pytest.fixture(scope="module")
def result():
    return compute_indicator(DEFINITION, altnrg_observations(), SSPI67)


# --- the seven datasets -------------------------------------------------------------------------


@pytest.mark.parametrize("code", ALTNRG_DATASETS)
def test_dataset_observations_match_the_legacy_cleaner(code):
    case, dataset, normalized = load_cases(OBSERVATION_CASES[code]), MetadataCatalog.load().dataset(code), iea_normalized()[code]
    product, label, count, nulls, zeros = EXPECTED[code]
    assert case["dataset_code"] == code and case["dimensions"] == {"product": product} == dataset.source.dimensions and case["product_label"] == [label]
    assert case["source_request"] == {"url": "https://api.iea.org/stats/indicator/TESbySource", "indicator": "TESbySource"} and dataset.source.query_code == "TESbySource"
    new = [observation_record(o) for o in normalized.observations]
    assert_parity(f"{code} observations", new, case["observations"], OBSERVATION_IDENTITY)
    assert summary(new) == summary(case["observations"]) and len(new) == count
    assert {o.unit for o in normalized.observations} == {"TJ"} == {dataset.unit} and {o.provenance["product"] for o in normalized.observations} == {product}
    assert [area for area, _ in normalized.skipped_areas] == case["skipped_areas"] and "WORLD" in case["skipped_areas"]
    assert (case["empty_source_values"], case["zero_source_values"]) == (nulls, zeros) and normalized.missing_values == nulls + zeros  # nulls and zeros are both dropped


def test_every_source_row_is_an_observation_a_dropped_value_or_a_skipped_area():
    rows = iea_rows()
    assert {r["product"] for r in rows} == {product for product, *_ in EXPECTED.values()} and {r["units"] for r in rows} == {"TJ"} and {r["flow"] for r in rows} == {"TES"}
    kept = sum(len(n.observations) for n in iea_normalized().values())
    dropped = sum(n.missing_values for n in iea_normalized().values())
    skipped = sum(1 for r in rows if r["country"] in ("WORLD", "GUYANA"))
    assert kept + dropped + skipped == len(rows) == 2034 and (kept, dropped, skipped) == (1684, 14, 336)
    assert {o.country_code for n in iea_normalized().values() for o in n.observations} == COUNTRIES  # Guyana is published as "GUYANA", not an ISO code: dropped, as in legacy
    assert (min(int(r["year"]) for r in rows), max(int(r["year"]) for r in rows)) == (1990, 2025)


# --- the indicator ------------------------------------------------------------------------------


def test_golden_file_records_the_legacy_facts():
    DEFINITION.check_against(MetadataCatalog.load())
    assert GOLDEN["indicator_code"] == "ALTNRG" and tuple(GOLDEN["dataset_codes"]) == ALTNRG_DATASETS == DEFINITION.dataset_codes
    assert GOLDEN["goalposts"] == [0, 60] == list(DEFINITION.goalposts) and GOLDEN["unit"] == "Index" == DEFINITION.unit
    assert GOLDEN["methodology_score_function"] == MetadataCatalog.load().indicator("ALTNRG").score_function
    assert GOLDEN["computed_series"] == {"dataset_code": altnrg.PERCENTAGE_CODE, "on_observed_scores": True, "on_imputed_scores": False}
    imputation, strategy = GOLDEN["imputation"], DEFINITION.imputation
    assert (imputation["backward_to"], imputation["forward_to"]) == strategy.years == tuple(imputation["zero_fill"]["years"]) == (2000, 2023)
    assert (imputation["zero_fill"]["recipient_group"], imputation["zero_fill"]["unit"]) == (strategy.recipient_group, strategy.fill_unit) == ("SSPI67", "PJ")
    assert "final energy supply from biofuel sources" in GOLDEN["methodology_description"]  # ALTNRG-1: the data are total energy supply


def test_legacy_output_is_consistent_so_exact_parity_is_required():
    assert legacy_inconsistency(GOLDEN) is None and GOLDEN["legacy_output_conflicts"] == {"observed_and_imputed": [], "duplicate_imputed": []}
    assert not any(code == "ALTNRG" for code, _ in list(INTENTIONAL_DIVERGENCES) + list(PENDING_METHODOLOGY_DECISIONS))


def test_observed_scores_and_the_derived_percentage_match_the_compute_route(result):
    assert_parity("ALTNRG observed scores", records(result.observed_scores), GOLDEN["observed_scores"])
    assert len(result.observed_scores) == 91 and not any(is_imputed(s) for s in result.observed_scores)
    for score in result.observed_scores:
        (percentage,) = score.computed
        values = {o.dataset_code: o.value for o in score.inputs}
        assert len(values) == 7 and percentage.dataset_code == "IEA_ALTNRG_PERCENTAGE" and percentage.value == altnrg.altnrg_percent_value(**values)
        assert score.score == altnrg.score_altnrg_observed(**values) == max(0.0, min(1.0, percentage.value / 60))
    assert {s.country_code for s in result.observed_scores} == {"JPN", "LTU", "PAK", "USA"}  # only countries with a nuclear row can be complete


def test_incomplete_observed_groups_match_the_compute_route():
    observed = score_indicator(altnrg_observations(), "ALTNRG", DEFINITION.observed_score, DEFINITION.unit, DEFINITION.computed_series)
    assert incomplete(observed.unscored) == GOLDEN["observed_incomplete"] and len(observed.unscored) == 193
    assert Counter(u.country_code for u in observed.unscored) == {"AUT": 36, "BOL": 35, "MYS": 35, "SGP": 35, "LTU": 28, "PAK": 23, "JPN": 1}
    assert all(u.computed == () for u in observed.unscored)  # no percentage without all seven


def test_imputed_scores_match_the_impute_route(result):
    assert_parity("ALTNRG imputed scores", records(result.imputed_scores), GOLDEN["imputed_scores"])
    assert len(result.imputed_scores) == 1518 and all(is_imputed(s) for s in result.imputed_scores)
    assert all(s.computed == () and s.provenance == {} and len(s.inputs) == 7 for s in result.imputed_scores)  # imputation is on the inputs
    methods = Counter(o.provenance["imputation_method"] for s in result.imputed_scores for o in s.inputs if o.provenance.get("imputed"))
    assert methods == {"Zero imputation for missing energy type": 10008, "Backward Extrapolation": 24, "Forward Extrapolation": 14, "Linear Interpolation": 8}
    assert {o.unit for s in result.imputed_scores for o in s.inputs if o.provenance.get("imputation_method") == altnrg.ZERO_FILL_METHOD} == {"PJ"}


def test_final_identity_set_and_incomplete_identities(result):
    legacy = {(r["country_code"], r["year"]) for key in ("observed_scores", "imputed_scores") for r in GOLDEN[key]}
    identities = [(s.country_code, s.year) for s in result.scores]
    assert len(identities) == len(set(identities)) == 91 + 1518 and set(identities) == legacy
    assert incomplete(result.unscored) == GOLDEN["incomplete_after_imputation"] and len(result.unscored) == 91
    left = Counter(u.country_code for u in result.unscored)
    assert left == {"BOL": 35, "AUT": 12, "LTU": 12, "MYS": 11, "SGP": 11, "PAK": 10}
    assert all(u.year < 2000 or u.year > 2023 for u in result.unscored if u.country_code != "BOL")  # members: only years outside the zero-fill window stay incomplete
    assert "BOL" not in SSPI67 and not any(s.country_code == "BOL" for s in result.scores)  # a non-member without nuclear is never scored


def test_behaviour_on_the_committed_rows(result):
    scores = {(s.country_code, s.year): s for s in result.scores}
    usa = scores[("USA", 2022)]
    assert not is_imputed(usa) and usa.computed[0].value == 100 * usa.score * 0.6 and 0 < usa.score < 1
    for country in ("MYS", "AUT", "SGP"):  # no nuclear row at all: every 2000-2023 score rests on a zero-filled input and is flagged imputed (ALTNRG-2)
        series = [scores[(country, year)] for year in range(2000, 2024)]
        assert all(is_imputed(s) for s in series)
        assert all(next(o for o in s.inputs if o.dataset_code == "IEA_NCLEAR").value == 0.0 for s in series)
    lithuania = next(o for o in scores[("LTU", 2020)].inputs if o.dataset_code == "IEA_NCLEAR")
    assert (lithuania.provenance["imputation_method"], lithuania.provenance["anchor_year"]) == ("Forward Extrapolation", 2009) and lithuania.value > 0  # the closed plant's last value, carried to 2023
    japan = next(o for o in scores[("JPN", 2014)].inputs if o.dataset_code == "IEA_NCLEAR")
    assert japan.provenance["imputation_method"] == "Linear Interpolation" and japan.provenance["anchor_years"] == [2013, 2015]  # the reported zero was dropped, the gap interpolated
    malaysia = next(o for o in scores[("MYS", 2000)].inputs if o.dataset_code == "IEA_GEOPWR")
    assert (malaysia.provenance["imputation_method"], malaysia.provenance["anchor_year"]) == ("Backward Extrapolation", 2001)
    absent = sorted(set(SSPI67) - COUNTRIES)
    assert len(absent) == 59 and all(scores[(c, y)].score == 0.0 and {o.unit for o in scores[(c, y)].inputs} == {"PJ"} for c in absent for y in (2000, 2023))  # fixture artefact: members absent from the sample are all zeros
    assert max(y for _, y in scores) == 2025 and min(y for _, y in scores) == 1990  # observed scores keep every year; nothing is imputed past 2023 except by interpolation
