"""Score parity: the orchestrated REDLST computation must reproduce the
legacy compute route exactly on the committed 15.5.1 fixture.

``redlst_cases.json`` was generated by ``generate_redlst_cases.py`` in the
old virtualenv at the pinned commit. Legacy REDLST has no impute route, so
the whole expected result is the compute route's output. The file records
the executable (0, 1) goalposts; the retired 2018 static data implies
(0.5, 1). See REDLST-1 in docs/methodology-conflicts.md.
"""

import json

import pytest

from sspi.imputation import is_imputed
from sspi.indicators import compute_indicator, registry
from sspi.indicators.redlst import score_redlst
from sspi.ingestion.unsdg import normalize_unsdg_dataset
from sspi.metadata import MetadataCatalog
from tests.golden.parity import INDICATOR_CASES, assert_parity, load_cases, score_records, source_fixtures

CASES = load_cases(INDICATOR_CASES["REDLST"])


@pytest.fixture(scope="module")
def observations():
    (fixture_path,) = source_fixtures(CASES)
    return normalize_unsdg_dataset(MetadataCatalog.load().dataset("UNSDG_REDLST"), json.loads(fixture_path.read_text())["data"]).observations


@pytest.fixture(scope="module")
def result(observations):
    return compute_indicator(registry.get("REDLST"), observations, recipients=())


def test_golden_file_records_the_legacy_facts():
    assert CASES["indicator_code"] == "REDLST"
    assert CASES["impute_route_exists"] is False and "0.5" in CASES["historical_discrepancy"]


def test_goalposts_are_the_ones_the_legacy_route_read():
    definition = registry.get("REDLST")
    assert tuple(definition.goalposts) == (CASES["goalposts"]["lower"], CASES["goalposts"]["upper"]) == (0, 1)


@pytest.mark.parametrize("case", CASES["goalpost_cases"], ids=[str(c["value"]) for c in CASES["goalpost_cases"]])
def test_score_function_matches_legacy(case):
    assert score_redlst(case["value"]) == case["score"]


def test_scores_match_the_legacy_compute_route(result):
    assert_parity("REDLST scores", score_records(result.observed_scores, imputation=False), CASES["scores"])
    assert len(result.observed_scores) == 230
    assert (min(s.score for s in result.scores), max(s.score for s in result.scores)) == (min(s["score"] for s in CASES["scores"]), max(s["score"] for s in CASES["scores"]))


def test_classification_matches_legacy(result):
    """No impute route: every score is observed, none is imputed."""
    assert result.imputed_scores == () and not any(is_imputed(s) for s in result.scores)
    assert all(s.unit == "Index" for s in result.scores)


def test_missingness_matches_legacy(result, observations):
    """One score per source observation, no incomplete group, nothing filled in."""
    assert len(result.unscored) == CASES["incomplete_count"] == 0
    assert {(s.country_code, s.year) for s in result.scores} == {(o.country_code, o.year) for o in observations}
