"""Differential test: the new UNSDG normalizer must reproduce the semantic
output of the legacy `extract_sdg` + `filter_sdg` cleaning for every migrated
UNSDG dataset, on the committed fixture rows.

Each `unsdg_<dataset>_cases.json` was generated by `generate_unsdg_cases.py`
in the old virtualenv (see `generated_from.commit`). Only (country, year,
value, unit) and the skipped areas are compared; the legacy document shape is
not.
"""

import json
from pathlib import Path

import pytest

from sspi.ingestion.unsdg import normalize_unsdg_dataset
from sspi.metadata import MetadataCatalog

HERE = Path(__file__).parent
CASE_FILES = sorted(HERE.glob("unsdg_*_cases.json"))
CASES = {path.stem: json.loads(path.read_text()) for path in CASE_FILES}


def test_every_ingestible_dataset_has_golden_cases():
    from sspi.ingestion import SUPPORTED_DATASETS

    assert {c["dataset_code"] for c in CASES.values()} == {"UNSDG_MARINE", "UNSDG_TERRST", "UNSDG_FRSHWT", "UNSDG_REDLST"} == set(SUPPORTED_DATASETS)


@pytest.mark.parametrize("case", CASES.values(), ids=[c["dataset_code"] for c in CASES.values()])
def test_fixture_records_its_provenance(case):
    meta = case["generated_from"]
    assert meta["repository"] == "sspi-data-webapp"
    assert len(meta["commit"]) == 40
    assert meta["working_tree_dirty"] is False
    assert (HERE.parent.parent / meta["fixture"]).exists()


@pytest.mark.parametrize("case", CASES.values(), ids=[c["dataset_code"] for c in CASES.values()])
def test_new_normalizer_matches_legacy_cleaner(case):
    dataset = MetadataCatalog.load().dataset(case["dataset_code"])
    assert dataset.source.organization_series_code == case["series_code"]
    fixture = json.loads((HERE.parent.parent / case["generated_from"]["fixture"]).read_text())
    result = normalize_unsdg_dataset(dataset, fixture["data"])

    new = [(o.country_code, o.year, o.value, o.unit) for o in result.observations]
    old = [(d["country_code"], d["year"], d["value"], d["unit"]) for d in case["observations"]]
    assert new == old  # exact values, exact order (both sorted by country, year)
    assert [list(a) for a in result.skipped_areas] == case["skipped_areas"]
