"""Parity for UIS_ENRPRI, UIS_ENRSEC, ENRPRI and ENRSEC against the legacy
cleaner and BOTH legacy routes on the committed UIS responses: observations,
observed scores (compute route), imputed scores (impute route: series fill
on the input, plus ENRSEC's China and Nigeria reference class), units,
input snapshots, identities and classification.

The goldens were generated by ``generate_education_cases.py`` in the old
virtualenv at the pinned commit, running the registered legacy cleaners and
the ``compute_*`` / ``impute_*`` view functions themselves. Every
comparison is exact; no tolerance.
"""

import json
from collections import Counter
from functools import cache
from pathlib import Path

import pytest

from sspi.imputation import REFERENCE_CLASS_AVERAGE, is_imputed
from sspi.indicators import compute_indicator, enrpri, enrsec, registry
from sspi.indicators.strategy import SeriesFillThenScore
from sspi.ingestion.runner import SUPPORTED_DATASETS, fetch_and_normalize, resolve_datasets
from sspi.ingestion.uis import UISIndicatorData
from sspi.metadata import MetadataCatalog
from tests.golden.parity import (
    INDICATOR_CASES,
    INTENTIONAL_DIVERGENCES,
    OBSERVATION_CASES,
    OBSERVATION_IDENTITY,
    PENDING_METHODOLOGY_DECISIONS,
    assert_parity,
    legacy_inconsistency,
    load_cases,
    observation_record,
    score_level_records,
)

UIS_DIRECTORY = Path(__file__).parents[1] / "fixtures" / "uis"
CATALOG = MetadataCatalog.load()
RELEASE = json.loads((UIS_DIRECTORY / "versions_default.json").read_text())["version"]
# indicator -> (dataset, UIS indicator, legacy cleaner description, score unit, goalposts, observations, observed, imputed)
CASES = {
    "ENRPRI": ("UIS_ENRPRI", "NERT.1.CP", "Net enrollment in primary school (%)", "%", [80, 100], 179, 179, 258),
    "ENRSEC": ("UIS_ENRSEC", "NERT.2.CP", "Net enrollment in lower secondary school (%)", "Percent", [70, 100], 120, 120, 255),
}
MODULES = {"ENRPRI": enrpri, "ENRSEC": enrsec}


def records(indicator):
    return json.loads((UIS_DIRECTORY / f"{indicator}_sample.json").read_text(encoding="utf-8"))["records"]


class FixtureClient:
    """Stands in for ``UISClient`` reading the release the fixtures were downloaded from; counts fetches."""

    def __init__(self):
        self.fetches = []

    def fetch_indicator(self, indicator):
        self.fetches.append(indicator)
        return UISIndicatorData(indicator, RELEASE, tuple(records(indicator)))


@cache
def normalized(dataset):
    client = FixtureClient()
    ((resolved, result),), _ = fetch_and_normalize(resolve_datasets([dataset], CATALOG), client, metadata=CATALOG)
    assert resolved.code == dataset and client.fetches == [CATALOG.dataset(dataset).source.query_code]
    return result


@cache
def run(indicator):
    return compute_indicator(registry.get(indicator), normalized(CASES[indicator][0]).observations)


@pytest.fixture(scope="module", params=sorted(CASES))
def case(request):
    code = request.param
    dataset = CASES[code][0]
    return code, load_cases(OBSERVATION_CASES[dataset]), load_cases(INDICATOR_CASES[code])


# --- datasets -----------------------------------------------------------------------------------


def test_datasets_are_the_uis_total_net_enrolment_rates(case):
    code, dataset_case, _ = case
    dataset, series, description, *_ = CASES[code]
    source = CATALOG.dataset(dataset).source
    assert dataset_case["source_indicator"] == series == source.query_code == source.organization_series_code and source.organization_code == "UIS"
    assert dataset in SUPPORTED_DATASETS and dataset_case["source_version"] == RELEASE
    assert dataset_case["descriptions"] == [description]  # the legacy cleaner's literal; UIS calls the series a *total* net enrolment rate (ENRPRI-1)
    assert {r["indicatorId"] for r in records(series)} == {series}  # one series, both sexes, no other dimension to select


def test_observations_match_the_legacy_cleaner_exactly(case):
    code, dataset_case, _ = case
    dataset, _, _, _, _, count, _, _ = CASES[code]
    result = normalized(dataset)
    assert_parity(f"{dataset} observations", [observation_record(o) for o in result.observations], dataset_case["observations"], OBSERVATION_IDENTITY)
    assert len(result.observations) == count and {o.unit for o in result.observations} == {"Percent"} == {CATALOG.dataset(dataset).unit}
    assert {o.provenance["source_version"] for o in result.observations} == {RELEASE}


def test_dropped_values_and_coverage_match_legacy(case):
    code, dataset_case, _ = case
    dataset, series, *_ = CASES[code]
    result = normalized(dataset)
    assert [list(s) for s in result.skipped_areas] == dataset_case["skipped_areas"] == []  # UIS serves national areas only, all ISO3
    assert result.missing_values == dataset_case["empty_source_values"] == 0
    assert len(records(series)) == len(result.observations) and not any(r["value"] == 0 for r in records(series))  # no zero in the source
    assert max(o.value for o in result.observations) == 100.0  # 100 is reached, never exceeded
    assert (min(o.year for o in result.observations), max(o.year for o in result.observations)) == (1970, 2024)  # no year filter
    qualifiers = Counter(o.provenance["qualifier"] for o in result.observations)
    assert set(qualifiers) == {None, "NAT_EST", "UIS_EST"}  # estimates are kept, as in legacy


# --- indicators ---------------------------------------------------------------------------------


def test_golden_files_record_the_legacy_facts(case):
    code, _, golden = case
    dataset, _, _, unit, goalposts, *_ = CASES[code]
    definition, module = registry.get(code), MODULES[code]
    definition.check_against(CATALOG)
    assert golden["formula"] == f"goalpost({dataset}, {goalposts[0]}, {goalposts[1]})" == golden["methodology_score_function"].removeprefix("Score = ")
    assert golden["goalposts"] == goalposts == list(definition.goalposts)
    assert golden["unit"] == golden["imputed_unit"] == unit == definition.unit == module.UNIT
    assert (golden["series_fill"]["backward_to"], golden["series_fill"]["forward_to"]) == module.SERIES_FILL_YEARS == definition.imputation.years
    assert definition.dataset_codes == (dataset,) and definition.score_dependencies == () and definition.auxiliary_datasets == () and definition.recipient_group is None


def test_legacy_output_is_consistent_so_exact_parity_is_required(case):
    code, _, golden = case
    assert legacy_inconsistency(golden) is None
    assert golden["legacy_output_conflicts"] == {"observed_and_imputed": [], "duplicate_imputed": []}
    assert not any(c == code for c, _ in list(INTENTIONAL_DIVERGENCES) + list(PENDING_METHODOLOGY_DECISIONS))


def test_observed_scores_match_the_compute_route(case):
    code, _, golden = case
    result = run(code)
    assert_parity(f"{code} observed scores", score_level_records(result.observed_scores), golden["observed_scores"])
    assert len(result.observed_scores) == CASES[code][6] and not any(is_imputed(s) for s in result.observed_scores)


def test_imputed_scores_match_the_impute_route(case):
    code, _, golden = case
    result = run(code)
    assert_parity(f"{code} imputed scores", score_level_records(result.imputed_scores), golden["imputed_scores"])
    assert len(result.imputed_scores) == CASES[code][7] and all(is_imputed(s) for s in result.imputed_scores)
    assert {s.unit for s in result.scores} == {CASES[code][3]}


def test_final_identity_set_classification_and_provenance(case):
    code, _, golden = case
    result = run(code)
    legacy = {(r["country_code"], r["year"]) for key in ("observed_scores", "imputed_scores") for r in golden[key]}
    identities = [(s.country_code, s.year) for s in result.scores]
    assert len(identities) == len(set(identities)) == CASES[code][6] + CASES[code][7] and set(identities) == legacy and result.unscored == ()
    assert all(s.provenance == {} for s in result.scores)  # imputation is on the input, never on the score
    formula = registry.get(code).observed_score
    for s in result.imputed_scores:
        (source,) = s.inputs
        assert source.provenance["imputed"] is True and s.score == formula(source.value)


# --- ENRPRI -------------------------------------------------------------------------------------


def test_enrpri_is_a_plain_series_fill_with_no_reference_class():
    definition = registry.get("ENRPRI")
    assert definition.imputation == SeriesFillThenScore(enrpri.score_enrpri, (2000, 2023)) and definition.imputation.listed_recipients == ()
    result = run("ENRPRI")
    assert Counter(s.inputs[0].provenance["imputation_method"] for s in result.imputed_scores) == {"Linear Interpolation": 132, "Forward Extrapolation": 104, "Backward Extrapolation": 22}
    scores = {(s.country_code, s.year): s for s in result.scores}
    # China's commented-out reference-class line stays inactive: China is carried forward from its last value, 1997
    china = scores[("CHN", 2023)].inputs[0].provenance
    assert (china["imputation_method"], china["anchor_year"], china["imputation_distance"]) == ("Forward Extrapolation", 1997, 26)
    assert not any(s.inputs[0].provenance.get("imputation_method") == REFERENCE_CLASS_AVERAGE for s in result.imputed_scores)
    nigeria = scores[("NGA", 2015)].inputs[0].provenance  # 2010 -> 2023 gap interpolated
    assert (nigeria["imputation_method"], nigeria["anchor_years"]) == ("Linear Interpolation", [2010, 2023])
    assert enrpri.score_enrpri(80) == 0.0 and enrpri.score_enrpri(100) == 1.0 and enrpri.score_enrpri(90) == 0.5


# --- ENRSEC -------------------------------------------------------------------------------------


def test_enrsec_reference_class_is_the_flat_mean_of_every_row_for_china_and_nigeria():
    golden = load_cases(INDICATOR_CASES["ENRSEC"])
    definition = registry.get("ENRSEC")
    assert definition.imputation == SeriesFillThenScore(enrsec.score_enrsec, (2000, 2023), listed_recipients=("CHN", "NGA"))
    rows = normalized("UIS_ENRSEC").observations
    mean = sum(o.value for o in rows) / len(rows)  # every country, every year from 1970, unweighted
    reference = golden["reference_class"]
    assert (reference["recipients"], reference["years"], reference["reference_count"], reference["mean"]) == (["CHN", "NGA"], [2000, 2023], 120, mean)
    result = run("ENRSEC")
    by_method = Counter(s.inputs[0].provenance["imputation_method"] for s in result.imputed_scores)
    assert by_method == {"Forward Extrapolation": 89, "Linear Interpolation": 78, REFERENCE_CLASS_AVERAGE: 48, "Backward Extrapolation": 40}
    for country in ("CHN", "NGA"):
        theirs = [s for s in result.scores if s.country_code == country]
        assert {s.year for s in theirs} == set(range(2000, 2024)) and all(is_imputed(s) for s in theirs)
        assert {(s.inputs[0].value, s.inputs[0].provenance["reference_observation_count"]) for s in theirs} == {(mean, 120)}
        assert {s.score for s in theirs} == {enrsec.score_enrsec(mean)}
    assert not any(o.country_code in ("CHN", "NGA") for o in rows)  # no collision on this release
