"""Parity for GTRANS against BOTH legacy routes on the committed IEA
``CO2BySector`` and World Bank population rows: observed scores (compute
route), imputed scores (impute route: the transport CO2 input carried
forward to 2023 inside the 2000-2023 window, scored against that year's
population), identities, incomplete groups and classification.

``gtrans_cases.json`` was generated by ``generate_ghg_cases.py`` in the old
virtualenv at the pinned commit, running the legacy cleaners and the
``compute_gtrans`` / ``impute_gtrans`` view functions themselves. Every
comparison is exact; no tolerance.
"""

import pytest

from sspi.imputation import is_imputed
from sspi.indicators import compute_indicator, gtrans, registry
from sspi.indicators.strategy import ExtrapolateInputsForwardThenScore
from sspi.metadata import CountryCatalog, MetadataCatalog
from sspi.scoring import score_indicator
from tests.golden.ghg import gtrans_observations
from tests.golden.parity import INDICATOR_CASES, INTENTIONAL_DIVERGENCES, PENDING_METHODOLOGY_DECISIONS, RESOLVED_METHODOLOGY_DECISIONS, assert_parity, legacy_inconsistency, load_cases, score_level_records

SSPI67 = tuple(CountryCatalog.load().group("SSPI67").members)
GOLDEN = load_cases(INDICATOR_CASES["GTRANS"])
DEFINITION = registry.get("GTRANS")


def incomplete(groups):
    return sorted(({"country_code": u.country_code, "year": u.year, "datasets": sorted(o.dataset_code for o in u.inputs)} for u in groups), key=lambda r: (r["country_code"], r["year"]))


@pytest.fixture(scope="module")
def result():
    return compute_indicator(DEFINITION, gtrans_observations(), SSPI67)


def test_golden_file_records_the_legacy_facts():
    DEFINITION.check_against(MetadataCatalog.load())
    assert GOLDEN["indicator_code"] == "GTRANS" and tuple(GOLDEN["dataset_codes"]) == DEFINITION.dataset_codes == ("IEA_TCO2EM", "WB_POPULN")
    assert GOLDEN["goalposts"] == [7000, 0] == list(DEFINITION.goalposts) and GOLDEN["unit"] == "Index" == DEFINITION.unit
    assert GOLDEN["methodology_score_function"] == "Score = goalpost(IEA_TCO2EM / WB_POPULN, 7000, 0)"
    assert "tonnes per inhabitant" in GOLDEN["methodology_description"]  # GTRANS-1: the computed ratio is kilograms per person
    strategy, imputation = DEFINITION.imputation, GOLDEN["imputation"]
    assert isinstance(strategy, ExtrapolateInputsForwardThenScore) and strategy.formula is gtrans.score_gtrans
    assert tuple(imputation["window"]) == strategy.years == (2000, 2023) and imputation["forward_to"] == 2023
    assert tuple(imputation["datasets_carried_forward"]) == strategy.datasets == ("IEA_TCO2EM",) and strategy.recipient_group is None


def test_legacy_output_is_consistent_so_exact_parity_is_required():
    assert legacy_inconsistency(GOLDEN) is None and GOLDEN["legacy_output_conflicts"] == {"observed_and_imputed": [], "duplicate_imputed": []}
    registered = list(INTENTIONAL_DIVERGENCES) + list(PENDING_METHODOLOGY_DECISIONS) + list(RESOLVED_METHODOLOGY_DECISIONS)
    assert not any(code == "GTRANS" for code, _ in registered)


def test_observed_scores_match_the_compute_route(result):
    assert_parity("GTRANS observed scores", score_level_records(result.observed_scores), GOLDEN["observed_scores"])
    assert len(result.observed_scores) == 270 and not any(is_imputed(s) for s in result.observed_scores)
    for score in result.observed_scores:
        values = {o.dataset_code: o.value for o in score.inputs}
        assert score.score == max(0.0, min(1.0, (values["IEA_TCO2EM"] / values["WB_POPULN"] - 7000) / (0 - 7000)))
    assert (min(s.year for s in result.observed_scores), max(s.year for s in result.observed_scores)) == (1990, 2024)  # no year filter


def test_incomplete_observed_groups_match_the_compute_route():
    observed = score_indicator(gtrans_observations(), "GTRANS", DEFINITION.observed_score, DEFINITION.unit)
    assert incomplete(observed.unscored) == GOLDEN["observed_incomplete"] and len(observed.unscored) == 593


def test_imputed_scores_match_the_impute_route(result):
    assert_parity("GTRANS imputed scores", score_level_records(result.imputed_scores), GOLDEN["imputed_scores"])
    assert [(s.country_code, s.year) for s in result.imputed_scores] == [("PAK", y) for y in range(2020, 2024)]
    for score in result.imputed_scores:
        co2 = next(o for o in score.inputs if o.dataset_code == "IEA_TCO2EM")
        population = next(o for o in score.inputs if o.dataset_code == "WB_POPULN")
        assert (co2.provenance["imputation_method"], co2.provenance["anchor_year"]) == ("Forward Extrapolation", 2019)
        assert not population.provenance.get("imputed") and population.year == score.year  # the year's own population, never imputed
        assert score.provenance == {} and is_imputed(score)


def test_incomplete_groups_after_imputation(result):
    """Inside 2000-2023: what the impute route's own scoring left incomplete. Outside: the compute route's groups,
    which the impute route never read."""
    inside = [u for u in result.unscored if 2000 <= u.year <= 2023]
    assert incomplete(inside) == GOLDEN["incomplete_after_imputation"] and len(inside) == 144
    outside = [r for r in GOLDEN["observed_incomplete"] if not 2000 <= r["year"] <= 2023]
    assert incomplete(u for u in result.unscored if not 2000 <= u.year <= 2023) == outside and len(result.unscored) == 144 + len(outside) == 589
    identities = [(s.country_code, s.year) for s in result.scores]
    assert len(identities) == len(set(identities)) == 274


def test_behaviour_on_the_committed_rows(result):
    scores = {(s.country_code, s.year): s for s in result.scores}
    assert {c for c, _ in scores} == {"AUT", "BOL", "KHM", "KWT", "MYS", "PAK", "SGP", "USA"}
    assert not any(c == "TWN" for c, _ in scores)  # IEA has Taiwan, the World Bank has no population for it: never scored
    assert ("PAK", 2024) not in scores  # forward extrapolation stops at 2023
    assert ("KHM", 1994) not in scores and ("KHM", 1995) in scores  # zero emissions dropped by the cleaner: unscored, not 1.0
    usa = scores[("USA", 2023)]
    per_person = next(o.value for o in usa.inputs if o.dataset_code == "IEA_TCO2EM") / next(o.value for o in usa.inputs if o.dataset_code == "WB_POPULN")
    assert 4000 < per_person < 6000 and 0.1 < usa.score < 0.5  # about 5 tonnes, i.e. 5,000 kg, per person (GTRANS-1)
