"""Parity for WATMAN against BOTH legacy routes on the committed 6.4.1 and
6.4.2 fixtures: observed scores (compute route), imputed scores and the
groups still incomplete (impute route), identities and classification.

``watman_cases.json`` was generated by ``generate_watman_cases.py`` in the old
virtualenv at the pinned commit, running the legacy cleaners, the legacy
``score_indicator`` and the legacy ``impute_watman`` view function itself.
Two variants: ``sgp_without_2005``, the source state the legacy route was
written against, on which both legacy routes run and exact parity is
required; and ``fixture_as_committed``, current source data on which the
legacy impute route raises, where the new backend applies the canonical-first
Singapore policy. The second is a registered intentional divergence
(``INTENTIONAL_DIVERGENCES``, WATMAN-3), not legacy parity.
"""

import json

import pytest

from sspi.imputation import is_imputed
from sspi.indicators import compute_indicator, registry
from sspi.indicators.watman import REFERENCE_CLASS_RECIPIENTS, SYNTHETIC_CWUEFF_RECIPIENTS, SYNTHETIC_METHOD
from sspi.ingestion.runner import fetch_and_normalize, resolve_datasets
from sspi.metadata import MetadataCatalog
from tests.golden.parity import INDICATOR_CASES, INTENTIONAL_DIVERGENCES, assert_parity, load_cases, score_records, source_fixtures

CASES = load_cases(INDICATOR_CASES["WATMAN"])
VARIANTS = {v["name"]: v for v in CASES["variants"]}


class _Client:
    def __init__(self, rows_by_query):
        self.rows_by_query = rows_by_query

    def fetch_indicator(self, code):
        return self.rows_by_query[code]


def blank_sgp_2005(rows):
    out = []
    for row in rows:
        row = dict(row)
        if row["geoAreaCode"] == "702" and row.get("activity") == "TOTAL":
            row["years"] = json.dumps([{"year": e["year"], "value": ""} if e["year"] == "[2005]" else e for e in json.loads(row["years"])])
        out.append(row)
    return out


def inputs_for(variant_name):
    catalog = MetadataCatalog.load()
    rows = {}
    for path in source_fixtures(CASES):
        fixture = json.loads(path.read_text())
        rows[fixture["indicator"]] = fixture["data"]
    if variant_name == "sgp_without_2005":
        rows["6.4.1"] = blank_sgp_2005(rows["6.4.1"])
    results, _ = fetch_and_normalize(resolve_datasets(["UNSDG_CWUEFF", "UNSDG_WTSTRS", "UNSDG_WUSEFF"], catalog), _Client(rows), metadata=catalog)
    by_code = {d.code: r.observations for d, r in results}
    return by_code["UNSDG_CWUEFF"] + by_code["UNSDG_WTSTRS"], by_code["UNSDG_WUSEFF"]


def test_golden_file_records_the_legacy_facts():
    assert CASES["indicator_code"] == "WATMAN" and CASES["impute_route_exists"] is True
    assert CASES["goalposts"] == {"UNSDG_CWUEFF": [-20, 50], "UNSDG_WTSTRS": [100, 0]}
    assert tuple(CASES["synthetic_cwueff_recipients"]) == SYNTHETIC_CWUEFF_RECIPIENTS and tuple(CASES["reference_class_recipients"]) == REFERENCE_CLASS_RECIPIENTS
    assert registry.get("WATMAN").auxiliary_datasets == ("UNSDG_WUSEFF",) and registry.get("WATMAN").recipient_group is None


def test_current_source_case_is_a_registered_intentional_divergence():
    """SGP has a derived CWUEFF series now; the legacy route's unconditional SGP reference class collides with it and the
    legacy route raises. The new backend applies the canonical-first policy (WATMAN-3). This is NOT legacy parity."""
    variant = VARIANTS["fixture_as_committed"]
    assert variant["legacy_impute_error"].startswith("InvalidDocumentFormatError: Duplicate dataset document")
    assert variant["imputed_scores"] is None and "SGP" in variant["cwueff_countries"]
    assert INTENTIONAL_DIVERGENCES[("WATMAN", "fixture_as_committed")] == "WATMAN-3"

    observations, auxiliary = inputs_for("fixture_as_committed")
    result = compute_indicator(registry.get("WATMAN"), observations, auxiliary=auxiliary)

    assert len(result.observed_scores) == 108 and len(result.imputed_scores) == 60 and result.unscored == ()
    assert_parity("WATMAN observed scores (current source)", score_records(result.observed_scores, imputation=True), variant["scores"])  # the compute route still agrees
    sgp = {s.year: s for s in result.scores if s.country_code == "SGP"}
    assert sorted(sgp) == list(range(2000, 2024))
    assert {y for y, s in sgp.items() if is_imputed(s)} == set(range(2000, 2006))  # canonical 2006-2023 wins; only the backward extrapolation is imputed
    methods = {o.provenance.get("imputation_method") for s in sgp.values() for o in s.inputs if o.dataset_code == "UNSDG_CWUEFF"}
    assert methods == {None, "Backward Extrapolation"}  # no reference-class row was created for SGP
    identities = [(s.country_code, s.year) for s in result.scores]
    assert len(identities) == len(set(identities))  # no duplicates, no observed/imputed collision
    assert sgp[2006].score == sgp[2000].score and next(o for o in sgp[2006].inputs if o.dataset_code == "UNSDG_CWUEFF").value == 17.75051124744378


@pytest.fixture(scope="module")
def result():
    observations, auxiliary = inputs_for("sgp_without_2005")
    return compute_indicator(registry.get("WATMAN"), observations, auxiliary=auxiliary)


@pytest.mark.parametrize("name", list(VARIANTS))
def test_observed_scores_match_the_compute_route(name):
    """The compute route has no imputation, so it is checked on both variants with a strategy-free definition."""
    from sspi.indicators import IndicatorDefinition
    from sspi.indicators.watman import score_watman

    variant = VARIANTS[name]
    observations, _ = inputs_for(name)
    observed = compute_indicator(IndicatorDefinition("WATMAN", score_watman, imputation=None), observations)
    assert_parity(f"WATMAN observed scores ({name})", score_records(observed.observed_scores, imputation=True), variant["scores"])
    assert sorted({(u.country_code, u.year) for u in observed.unscored}) == [tuple(i) for i in variant["incomplete_identities"]]
    assert not any(is_imputed(s) for s in observed.observed_scores)


def test_observed_pass_is_identical_with_the_strategy_attached(result):
    variant = VARIANTS["sgp_without_2005"]
    assert_parity("WATMAN observed scores (with strategy)", score_records(result.observed_scores, imputation=True), variant["scores"])


def test_imputed_scores_match_the_impute_route(result):
    variant = VARIANTS["sgp_without_2005"]
    assert variant["legacy_impute_error"] is None
    assert_parity("WATMAN imputed scores", score_records(result.imputed_scores, imputation=True), variant["imputed_scores"])
    assert len(result.imputed_scores) == 78
    assert sorted({(u.country_code, u.year) for u in result.unscored}) == [tuple(i) for i in variant["imputed_incomplete_identities"]] == []
    assert all(is_imputed(s) for s in result.imputed_scores) and not any(is_imputed(s) for s in result.observed_scores)
    assert {(s.country_code, s.year) for s in result.observed_scores}.isdisjoint({(s.country_code, s.year) for s in result.imputed_scores})


def test_headline_imputation_paths(result):
    by_country = {}
    for s in result.imputed_scores:
        by_country.setdefault(s.country_code, []).append(s)
    che = {s.year: s for s in by_country["CHE"]}
    sgp = {s.year: s for s in by_country["SGP"]}
    assert sorted(che) == list(range(2000, 2024)) and sorted(sgp) == list(range(2000, 2024))
    che_cwueff = next(o for o in che[2010].inputs if o.dataset_code == "UNSDG_CWUEFF")
    assert che_cwueff.provenance["imputation_method"] == SYNTHETIC_METHOD and che_cwueff.provenance["derived_from"] == "UNSDG_WUSEFF"
    sgp_cwueff = next(o for o in sgp[2010].inputs if o.dataset_code == "UNSDG_CWUEFF")
    assert sgp_cwueff.provenance["imputation_method"] == "ImputeReferenceClassAverage"
    # countries with a derived series get only the extrapolated 2000-2005 years imputed
    mys = sorted(s.year for s in by_country["MYS"])
    assert mys == list(range(2000, 2006))
    assert all(o.provenance.get("imputation_method") == "Backward Extrapolation" for s in by_country["MYS"] for o in s.inputs if o.dataset_code == "UNSDG_CWUEFF")
