"""Parity for CARBON against BOTH legacy routes on the committed FAO Land Use
bulk-file sample: observed scores (compute route, level rows from 2000),
input-level imputed scores (impute route: reference-class means of both
inputs for KWT/BEL/LUX, scored with the ordinary formula), identities and
classification.

``carbon_cases.json`` was generated by ``generate_fao_land_cases.py`` in the
old virtualenv at the pinned commit, running the legacy cleaners, the legacy
``score_indicator`` and the legacy ``impute_carbon`` view function itself.
Two variants: ``without_kwt_source_rows``, the source state the route's
hard-coded recipient list was written against, on which exact parity is
required; and ``fixture_as_committed``, current source data on which the
legacy route stores an observed and an imputed score for the same KWT
country-years. That variant is a pending methodology decision
(``PENDING_METHODOLOGY_DECISIONS``, CARBON-1), not a divergence: the new
backend raises and selects no result.
"""

import pytest

from sspi.errors import ImputationError
from sspi.imputation import is_imputed
from sspi.indicators import IndicatorDefinition, compute_indicator, registry
from sspi.indicators.carbon import REFERENCE_CLASS_RECIPIENTS, keep_for_scoring, score_carbon
from sspi.ingestion.fao import read_bulk_csv
from sspi.ingestion.runner import fetch_and_normalize, resolve_datasets
from sspi.metadata import MetadataCatalog
from tests.golden.parity import INDICATOR_CASES, INTENTIONAL_DIVERGENCES, PENDING_METHODOLOGY_DECISIONS, assert_parity, legacy_inconsistency, load_cases, score_level_records, source_fixtures

CASES = load_cases(INDICATOR_CASES["CARBON"])
VARIANTS = {v["name"]: v for v in CASES["variants"]}
PARITY_VARIANT = "without_kwt_source_rows"


class _BulkClient:
    def __init__(self, rows):
        self.rows = rows

    def fetch_domain(self, domain):
        return self.rows


def observations_for(variant_name):
    catalog = MetadataCatalog.load()
    (path,) = source_fixtures(CASES)
    rows = read_bulk_csv(path.read_text(encoding="utf-8"), "RL")
    if variant_name == PARITY_VARIANT:
        rows = [r for r in rows if r["Area"] != "Kuwait"]
    results, _ = fetch_and_normalize(resolve_datasets(["UNFAO_CRBNLV", "UNFAO_CRBNAV"], catalog), _BulkClient(rows), metadata=catalog)
    return tuple(o for _, r in results for o in r.observations)


def test_golden_file_records_the_legacy_facts():
    assert CASES["indicator_code"] == "CARBON" and CASES["impute_route_exists"] is True
    assert CASES["goalposts"] == [-5.0, 50.0] == list(registry.get("CARBON").goalposts)
    assert CASES["level_year_filter"] == ">= 2000"
    assert tuple(CASES["reference_class_recipients"]) == REFERENCE_CLASS_RECIPIENTS
    assert registry.get("CARBON").auxiliary_datasets == () and registry.get("CARBON").recipient_group is None


def test_current_source_case_is_a_pending_methodology_decision_with_no_result_selected():
    """KWT has carbon-stock rows now. The legacy impute route still gives it reference-class inputs for 2000-2023, so its
    output holds an observed and an imputed score for KWT 2000-2023. No precedence has been decided; the new backend
    raises and selects nothing (CARBON-1)."""
    variant = VARIANTS["fixture_as_committed"]
    assert variant["legacy_impute_error"] is None
    conflicts = variant["legacy_output_conflicts"]
    assert conflicts["observed_and_imputed"] == [["KWT", y] for y in range(2000, 2024)] and conflicts["duplicate_imputed"] == []
    assert legacy_inconsistency(variant) and PENDING_METHODOLOGY_DECISIONS[("CARBON", "fixture_as_committed")] == "CARBON-1"
    assert ("CARBON", "fixture_as_committed") not in INTENTIONAL_DIVERGENCES  # no replacement methodology approved: nothing selected

    observations = observations_for("fixture_as_committed")
    observed = compute_indicator(IndicatorDefinition("CARBON", score_carbon, imputation=None, observation_filter=keep_for_scoring), observations)
    assert_parity("CARBON observed scores (current source)", score_level_records(observed.observed_scores), variant["scores"])
    with pytest.raises(ImputationError, match=r"CARBON-1") as info:
        compute_indicator(registry.get("CARBON"), observations)
    message = str(info.value)
    assert "KWT" in message and "source data has changed" in message and "No precedence" in message and "Methodology review is required" in message


@pytest.fixture(scope="module")
def result():
    return compute_indicator(registry.get("CARBON"), observations_for(PARITY_VARIANT))


def test_parity_variant_is_consistent_legacy_output():
    assert legacy_inconsistency(VARIANTS[PARITY_VARIANT]) is None


def test_observed_scores_match_the_compute_route(result):
    variant = VARIANTS[PARITY_VARIANT]
    assert_parity("CARBON observed scores", score_level_records(result.observed_scores), variant["scores"])
    assert len(result.observed_scores) == 283
    assert not any(is_imputed(s) for s in result.observed_scores)
    assert (min(s.year for s in result.observed_scores), max(s.year for s in result.observed_scores)) == (2000, 2025)  # the carbon average follows the source (DEFRST-2)


def test_incomplete_identities_match_the_compute_route(result):
    variant = VARIANTS[PARITY_VARIANT]
    legacy_incomplete = {tuple(i) for i in variant["incomplete_identities"]}
    filled = {(s.country_code, s.year) for s in result.imputed_scores}
    assert {(u.country_code, u.year) for u in result.unscored} == legacy_incomplete - filled
    observed_only = compute_indicator(IndicatorDefinition("CARBON", score_carbon, imputation=None, observation_filter=keep_for_scoring), observations_for(PARITY_VARIANT))
    assert {(u.country_code, u.year) for u in observed_only.unscored} == legacy_incomplete


def test_imputed_scores_match_the_impute_route(result):
    variant = VARIANTS[PARITY_VARIANT]
    assert_parity("CARBON imputed scores", score_level_records(result.imputed_scores), variant["imputed_scores"])
    assert len(result.imputed_scores) == 72
    assert all(is_imputed(s) for s in result.imputed_scores) and not any(s.provenance.get("imputed") for s in result.imputed_scores)  # imputed inputs, not scores
    assert {(s.country_code, s.year) for s in result.observed_scores}.isdisjoint({(s.country_code, s.year) for s in result.imputed_scores})


def test_imputed_inputs_are_the_legacy_reference_means(result):
    observations = observations_for(PARITY_VARIANT)
    level = [o for o in observations if o.dataset_code == "UNFAO_CRBNLV"]
    average = [o for o in observations if o.dataset_code == "UNFAO_CRBNAV"]
    assert {s.country_code for s in result.imputed_scores} == set(REFERENCE_CLASS_RECIPIENTS)
    for s in result.imputed_scores:
        assert 2000 <= s.year <= 2023
        by_code = {o.dataset_code: o for o in s.inputs}
        assert by_code["UNFAO_CRBNLV"].value == sum(o.value for o in level) / len(level)  # every country, every year, 1990s included
        assert by_code["UNFAO_CRBNAV"].value == sum(o.value for o in average) / len(average)
        assert all(o.provenance["imputation_method"] == "ImputeReferenceClassAverage" for o in s.inputs)
        assert s.score == score_carbon(by_code["UNFAO_CRBNLV"].value, by_code["UNFAO_CRBNAV"].value)
