"""Parity for GINIPT against BOTH legacy routes on the committed World Bank
and WID fixtures, stage by stage:

    A  source cleaning            test_golden_inequality_datasets.py
    B  observed scoring           compute route
    C  series fill                impute route, stage 1 (inputs)
    D  regression training set    the identities the legacy fit saw
    E  fitted parameters          legacy sklearn coefficient and intercept
    F  predicted identities       recipients and years
    G  predicted scores           impute route, stage 2 (scores)
    H  final identity set
    I  classification, provenance

``ginipt_cases.json`` was generated by ``generate_inequality_cases.py`` in the
old virtualenv at the pinned commit, running the legacy cleaners,
``compute_ishrat``, ``compute_ginipt`` and ``impute_ginipt`` themselves, with
the legacy scikit-learn fit observed through a recording subclass. Every
comparison is exact; no tolerance.
"""

import pytest

from sspi.errors import ScoreDependencyError
from sspi.imputation import is_imputed
from sspi.indicators import IndicatorDefinition, compute_indicator, registry
from sspi.indicators.ginipt import FEATURE_INDICATOR, REGRESSION_DETAILS, REGRESSION_MODEL, SERIES_FILL_YEARS, UNIT, score_ginipt
from sspi.indicators.strategy import REGRESSION_IMPUTATION, fit_centered_least_squares
from tests.golden.inequality import wb_observations, wid_observations
from tests.golden.parity import INDICATOR_CASES, INTENTIONAL_DIVERGENCES, PENDING_METHODOLOGY_DECISIONS, assert_parity, legacy_inconsistency, load_cases, score_level_records

CASES = load_cases(INDICATOR_CASES["GINIPT"])
REGRESSION = CASES["regression"]
RECIPIENTS = ["KWT", "NZL", "SAU", "SGP"]


@pytest.fixture(scope="module")
def ishrat():
    return compute_indicator(registry.get("ISHRAT"), wid_observations())


@pytest.fixture(scope="module")
def result(ishrat):
    return compute_indicator(registry.get("GINIPT"), wb_observations(), dependency_scores={"ISHRAT": ishrat.scores})


@pytest.fixture(scope="module")
def series_fill(result):
    return [s for s in result.imputed_scores if not s.provenance.get("imputed")]


@pytest.fixture(scope="module")
def predicted(result):
    return [s for s in result.imputed_scores if s.provenance.get("imputed")]


def test_golden_file_records_the_legacy_facts():
    definition = registry.get("GINIPT")
    assert CASES["indicator_code"] == "GINIPT" and CASES["impute_route_exists"] is True and definition.imputes
    assert CASES["goalposts"] == [70, 20] == list(definition.goalposts)  # lower > upper: inverted scale
    assert CASES["formula"] == "goalpost(WB_GINIPT, 70, 20)" and CASES["unit"] == UNIT == definition.unit == "Coefficient"
    assert CASES["series_fill"]["backward_to"] == SERIES_FILL_YEARS[0] == 2000 and CASES["series_fill"]["forward_to"] == SERIES_FILL_YEARS[1] == 2023
    assert REGRESSION["feature_indicator"] == FEATURE_INDICATOR == "ISHRAT" and definition.score_dependencies == ("ISHRAT",)
    assert REGRESSION["model_string"] == REGRESSION_MODEL and REGRESSION["details"] == REGRESSION_DETAILS
    assert definition.auxiliary_datasets == () and definition.recipient_group is None  # no country group: recipients come from the data


def test_legacy_output_is_consistent_so_exact_parity_is_required():
    assert legacy_inconsistency(CASES) is None
    assert CASES["legacy_output_conflicts"] == {"observed_and_imputed": [], "duplicate_imputed": []}
    assert not any(code == "GINIPT" for code, _ in list(INTENTIONAL_DIVERGENCES) + list(PENDING_METHODOLOGY_DECISIONS))


# --- B: observed scoring ----------------------------------------------------------------------


def test_observed_scores_match_the_compute_route(result):
    assert_parity("GINIPT observed scores", score_level_records(result.observed_scores), CASES["observed_scores"])
    assert len(result.observed_scores) == 1727 and not any(is_imputed(s) for s in result.observed_scores)
    assert (min(s.year for s in result.observed_scores), max(s.year for s in result.observed_scores)) == (1963, 2025)  # no year filter
    assert len({s.country_code for s in result.observed_scores}) == 87  # no SSPI67 filter


def test_observed_scoring_alone_needs_no_dependency(result):
    """The compute route by itself: the formula with no impute route and no score dependency."""
    observed_only = compute_indicator(IndicatorDefinition("GINIPT", score_ginipt, imputation=None, unit=UNIT), wb_observations())
    assert observed_only.observed_scores == result.observed_scores and observed_only.imputed_scores == ()


def test_out_of_goalpost_value_is_clamped(result):
    namibia = next(s for s in result.observed_scores if (s.country_code, s.year) == ("NAM", 1993))
    assert namibia.inputs[0].value == 71.1 and namibia.score == 0.0


# --- C: series fill ---------------------------------------------------------------------------


def test_series_fill_scores_match_the_impute_route(series_fill):
    assert_parity("GINIPT series-fill scores", score_level_records(series_fill), CASES["series_fill_scores"])
    assert len(series_fill) == 1371 and all(is_imputed(s) for s in series_fill)


def test_series_fill_methods_and_year_behaviour(series_fill):
    methods = {}
    for s in series_fill:
        (source,) = s.inputs
        methods.setdefault(source.provenance["imputation_method"], []).append(s)
    assert {m: len(v) for m, v in methods.items()} == {"Forward Extrapolation": 169, "Backward Extrapolation": 80, "Linear Interpolation": 1122}
    assert max(s.year for s in methods["Forward Extrapolation"]) == 2023 and min(s.year for s in methods["Backward Extrapolation"]) == 2000
    assert all(s.inputs[0].provenance["anchor_year"] < s.year for s in methods["Forward Extrapolation"])
    assert all(s.inputs[0].provenance["anchor_year"] > s.year for s in methods["Backward Extrapolation"])
    # interpolation is not bounded by 2000-2023 (GINIPT-3): gaps before 2000 are filled too
    assert sum(1 for s in series_fill if s.year < 2000) == 551 and min(s.year for s in series_fill) == 1971
    assert all(s.inputs[0].provenance["imputation_method"] == "Linear Interpolation" for s in series_fill if s.year < 2000)
    assert not any(s.year > 2023 for s in series_fill)
    assert len({s.country_code for s in series_fill}) > 66  # every country in the dataset, not a country group


# --- D, E: regression training and fit --------------------------------------------------------


def test_training_set_is_the_inner_join_the_legacy_fit_saw(result, ishrat):
    """Observed ISHRAT scores joined with observed GINIPT scores by (country, year), pooled, in (country, year) order."""
    features = {(s.country_code, s.year): s.score for s in ishrat.scores}
    targets = {(s.country_code, s.year): s.score for s in result.observed_scores}
    training = [{"country_code": c, "year": y, "feature_score": features[(c, y)], "target_score": targets[(c, y)]} for c, y in sorted(set(features) & set(targets))]
    assert training == REGRESSION["training"] and len(training) == 1077
    assert len({t["country_code"] for t in training}) == 62 and {t["year"] for t in training} <= set(range(2000, 2025))


def test_fitted_parameters_equal_the_legacy_sklearn_fit_exactly():
    coefficient, intercept = fit_centered_least_squares((t["feature_score"] for t in REGRESSION["training"]), (t["target_score"] for t in REGRESSION["training"]))
    assert coefficient == REGRESSION["coefficient"] == 0.6319038133391379
    assert intercept == REGRESSION["intercept"] == 0.520623232586591


# --- F, G: predictions ------------------------------------------------------------------------


def test_recipients_are_the_countries_with_no_gini_data(result, predicted, ishrat):
    assert sorted({s.country_code for s in predicted}) == REGRESSION["recipients"] == RECIPIENTS
    with_gini = {o.country_code for o in wb_observations()}
    assert sorted({s.country_code for s in ishrat.scores} - with_gini) == RECIPIENTS  # derived from the data, not from a list


def test_prediction_identities_and_inputs_match_legacy(predicted):
    legacy = REGRESSION["prediction_inputs"]
    assert [(s.country_code, s.year) for s in predicted] == [(p["country_code"], p["year"]) for p in legacy]
    assert [s.provenance["feature_score"] for s in predicted] == [p["feature_score"] for p in legacy]
    assert [s.provenance["raw_prediction"] for s in predicted] == [p["raw_prediction"] for p in legacy]
    assert len(predicted) == 100 and {s.year for s in predicted} == set(range(2000, 2025))  # every ISHRAT year, 2024 included (GINIPT-3)


def test_predicted_scores_match_the_impute_route(predicted):
    new = []
    for record, score in zip(score_level_records(predicted), predicted):
        lower, upper = score.provenance["goalposts"]
        new.append(dict(record, value=score.provenance["implied_value"], lower_goalpost=lower, upper_goalpost=upper))
    assert_parity("GINIPT regression-predicted scores", new, REGRESSION["predicted_scores"])
    assert all(0.0 <= s.score <= 1.0 for s in predicted)


# --- H, I: final set, classification, provenance ----------------------------------------------


def test_final_identity_set_is_the_union_of_both_legacy_routes(result):
    legacy = {(r["country_code"], r["year"]) for key in ("observed_scores", "series_fill_scores") for r in CASES[key]} | {(r["country_code"], r["year"]) for r in REGRESSION["predicted_scores"]}
    identities = [(s.country_code, s.year) for s in result.scores]
    assert len(identities) == len(set(identities)) == 1727 + 1371 + 100 and set(identities) == legacy
    assert result.unscored == ()


def test_classification_and_stage_provenance(result, series_fill, predicted):
    assert all(not is_imputed(s) and s.provenance == {} for s in result.observed_scores)
    for s in series_fill:  # imputed through its input; the score itself was produced by the ordinary formula
        (source,) = s.inputs
        assert s.provenance == {} and source.dataset_code == "WB_GINIPT" and source.provenance["imputed"] is True
        assert source.provenance["imputation_distance"] >= 1 and s.score == score_ginipt(source.value)
    for s in predicted:  # imputed at score level; no observation fabricated
        assert s.inputs == () and s.computed == () and is_imputed(s)
        assert s.provenance["imputation_method"] == REGRESSION_IMPUTATION == "RegressionImputation" and s.provenance["imputation_distance"] == 0
        assert s.provenance["feature_indicator"] == "ISHRAT" and s.provenance["regression_model"] == REGRESSION_MODEL
        assert s.provenance["training_score_count"] == 1077 and s.provenance["imputation_details"] == REGRESSION_DETAILS
        assert s.provenance["coefficient"] == REGRESSION["coefficient"] and s.provenance["intercept"] == REGRESSION["intercept"]


def test_the_complete_run_refuses_without_ishrat_scores():
    with pytest.raises(ScoreDependencyError, match=r"GINIPT requires existing ISHRAT scores.*Run ISHRAT first"):
        compute_indicator(registry.get("GINIPT"), wb_observations())
