"""Parity for EMPLOY and COLBAR against BOTH legacy routes on the committed
ILO responses: observed scores (compute route), imputed scores (impute
route: series fill on the inputs), units, identities and classification.

``employ_cases.json`` and ``colbar_cases.json`` were generated by
``generate_worker_engagement_cases.py`` in the old virtualenv at the pinned
commit, running the legacy cleaners and the ``compute_*`` / ``impute_*``
view functions themselves. Every comparison is exact; no tolerance.
"""

from collections import Counter

import pytest

from sspi.imputation import is_imputed
from sspi.indicators import colbar, compute_indicator, employ, registry
from sspi.indicators.strategy import SeriesFillThenScore
from sspi.metadata import CountryCatalog, MetadataCatalog
from tests.golden.parity import INDICATOR_CASES, INTENTIONAL_DIVERGENCES, PENDING_METHODOLOGY_DECISIONS, assert_parity, legacy_inconsistency, load_cases, score_level_records
from tests.golden.worker_engagement import CASES, observations

MODULES = {"EMPLOY": employ, "COLBAR": colbar}
EXPECTED = {
    "EMPLOY": {"formula": "goalpost(ILO_EMPLOY_TO_POP, 50, 95)", "goalposts": [50, 95], "unit": "Percentage", "observed": 2690, "imputed": 2576},
    "COLBAR": {"formula": "goalpost(ILO_COLBAR, 0, 100)", "goalposts": [0, 100], "unit": "%", "observed": 865, "imputed": 1511},
}
SSPI67 = set(CountryCatalog.load().group("SSPI67").members)


@pytest.fixture(scope="module", params=sorted(CASES))
def case(request):
    code = request.param
    return code, load_cases(INDICATOR_CASES[code]), compute_indicator(registry.get(code), observations(code))


def test_golden_file_records_the_legacy_facts(case):
    code, golden, _ = case
    definition, expected, module = registry.get(code), EXPECTED[code], MODULES[code]
    definition.check_against(MetadataCatalog.load())
    assert golden["indicator_code"] == code and golden["impute_route_exists"] is True and definition.imputes
    assert golden["formula"] == expected["formula"] and golden["methodology_score_function"] == f"Score = {expected['formula']}"
    assert golden["goalposts"] == expected["goalposts"] == list(definition.goalposts)
    assert golden["unit"] == expected["unit"] == definition.unit == module.UNIT
    assert golden["imputed_unit"] == "Tax Rate" == module.IMPUTED_UNIT  # the impute route's own literal, reproduced
    assert isinstance(definition.imputation, SeriesFillThenScore) and definition.imputation.unit == "Tax Rate"
    assert (golden["series_fill"]["backward_to"], golden["series_fill"]["forward_to"]) == module.SERIES_FILL_YEARS == definition.imputation.years == (2000, 2023)
    assert definition.dataset_codes == (CASES[code][0],) and definition.score_dependencies == ()
    assert definition.auxiliary_datasets == () and definition.recipient_group is None  # no reference class, no country group


def test_legacy_output_is_consistent_so_exact_parity_is_required(case):
    code, golden, _ = case
    assert legacy_inconsistency(golden) is None
    assert golden["legacy_output_conflicts"] == {"observed_and_imputed": [], "duplicate_imputed": []}
    assert not any(c == code for c, _ in list(INTENTIONAL_DIVERGENCES) + list(PENDING_METHODOLOGY_DECISIONS))


def test_observed_scores_match_the_compute_route(case):
    code, golden, result = case
    assert_parity(f"{code} observed scores", score_level_records(result.observed_scores), golden["observed_scores"])
    assert len(result.observed_scores) == EXPECTED[code]["observed"] and not any(is_imputed(s) for s in result.observed_scores)
    assert {s.unit for s in result.observed_scores} == {EXPECTED[code]["unit"]}


def test_imputed_scores_match_the_impute_route(case):
    code, golden, result = case
    assert_parity(f"{code} imputed scores", score_level_records(result.imputed_scores), golden["imputed_scores"])
    assert len(result.imputed_scores) == EXPECTED[code]["imputed"] and all(is_imputed(s) for s in result.imputed_scores)
    assert {s.unit for s in result.imputed_scores} == {"Tax Rate"}


def test_final_identity_set_classification_and_provenance(case):
    code, golden, result = case
    legacy = {(r["country_code"], r["year"]) for key in ("observed_scores", "imputed_scores") for r in golden[key]}
    identities = [(s.country_code, s.year) for s in result.scores]
    assert len(identities) == len(set(identities)) == EXPECTED[code]["observed"] + EXPECTED[code]["imputed"] and set(identities) == legacy
    assert result.unscored == ()
    assert all(s.provenance == {} for s in result.scores)  # imputation is on the input, never on the score
    formula = registry.get(code).observed_score
    for s in result.imputed_scores:
        (source,) = s.inputs
        assert source.provenance["imputed"] is True and source.provenance["imputation_distance"] >= 1 and s.score == formula(source.value)
    observed_areas = {s.country_code for s in result.observed_scores}
    assert {s.country_code for s in result.imputed_scores} <= observed_areas  # an area with no observation gets nothing


def methods(result):
    by_method = {}
    for s in result.imputed_scores:
        by_method.setdefault(s.inputs[0].provenance["imputation_method"], []).append(s)
    return by_method


def test_employ_series_fill_behaviour():
    result = compute_indicator(registry.get("EMPLOY"), observations("EMPLOY"))
    by_method = methods(result)
    assert {m: len(v) for m, v in by_method.items()} == {"Forward Extrapolation": 510, "Backward Extrapolation": 1073, "Linear Interpolation": 993}
    assert max(s.year for s in by_method["Forward Extrapolation"]) == 2023 and min(s.year for s in by_method["Backward Extrapolation"]) == 2000
    assert (min(s.year for s in result.observed_scores), max(s.year for s in result.observed_scores)) == (2000, 2025)  # no year filter on observed scores
    assert max(s.year for s in result.imputed_scores) == 2024  # a 2023-2025 gap is interpolated; nothing is carried past 2023
    assert all(s.inputs[0].provenance["imputation_method"] == "Linear Interpolation" for s in result.imputed_scores if s.year > 2023)
    assert SSPI67 <= {s.country_code for s in result.scores} and len({s.country_code for s in result.scores}) == 211
    counts = Counter(s.country_code for s in result.scores if 2000 <= s.year <= 2023)
    assert all(counts[c] == 24 for c in SSPI67)  # every SSPI67 member has a full 2000-2023 series after the fill
    austria = next(s for s in result.observed_scores if (s.country_code, s.year) == ("AUT", 2023))
    assert austria.inputs[0].value == 73.804 and austria.score == (73.804 - 50) / (95 - 50)


def test_colbar_series_fill_behaviour():
    result = compute_indicator(registry.get("COLBAR"), observations("COLBAR"))
    by_method = methods(result)
    assert {m: len(v) for m, v in by_method.items()} == {"Forward Extrapolation": 583, "Backward Extrapolation": 711, "Linear Interpolation": 217}
    assert (min(s.year for s in result.imputed_scores), max(s.year for s in result.imputed_scores)) == (2000, 2023)
    assert max(s.year for s in result.observed_scores) == 2020  # the source stops in 2020: every 2021-2023 score is carried forward
    assert all(is_imputed(s) for s in result.scores if s.year > 2020)
    scored = {s.country_code for s in result.scores}
    assert len(scored) == 99 and sorted(SSPI67 - scored) == ["ARE", "DZA", "ECU", "IND", "IRN", "IRQ", "KWT", "NGA", "PAK", "SAU"]  # COLBAR-1: no score at all
    malaysia = {s.year: s for s in result.scores if s.country_code == "MYS"}
    assert malaysia[2018].inputs[0].value == 0.4 and malaysia[2018].score == 0.4 / 100 and not is_imputed(malaysia[2018])
    assert is_imputed(malaysia[2023]) and malaysia[2023].score == malaysia[2018].score and malaysia[2023].inputs[0].provenance["anchor_year"] == 2018
    assert malaysia[2018].unit == "%" and malaysia[2023].unit == "Tax Rate"  # COLBAR-2
