"""Observation parity: the new UNSDG normalizer must reproduce the semantic
output of the legacy `extract_sdg` + `filter_sdg` cleaning for every
ingestible UNSDG dataset, from the same committed source fixture.

Each `unsdg_<dataset>_cases.json` was generated by `generate_unsdg_cases.py`
in the old virtualenv at the pinned commit. Identity is
(dataset_code, country_code, year); value and unit are compared exactly. The
legacy clean documents carry no per-observation source flags (its extractor
reads row-level fields only), so there is no legacy provenance to compare;
the legacy document shape is not compared either.
"""

import json

import pytest

from sspi.ingestion.unsdg import normalize_unsdg_dataset
from sspi.metadata import MetadataCatalog
from tests.golden.parity import OBSERVATION_CASES, OBSERVATION_IDENTITY, assert_parity, load_cases, observation_record, source_fixtures, summary

CASES = {code: load_cases(filename) for code, filename in OBSERVATION_CASES.items()}


@pytest.fixture(scope="module", params=list(CASES), ids=list(CASES))
def parity(request):
    case = CASES[request.param]
    dataset = MetadataCatalog.load().dataset(request.param)
    (fixture_path,) = source_fixtures(case)
    rows = json.loads(fixture_path.read_text())["data"]
    return case, dataset, rows, normalize_unsdg_dataset(dataset, rows)


def test_golden_file_describes_this_dataset(parity):
    case, dataset, _, _ = parity
    assert case["dataset_code"] == dataset.code
    assert dataset.source.organization_series_code == case["series_code"]


def test_observations_match_legacy_cleaner(parity):
    case, dataset, _, result = parity
    assert {o.dataset_code for o in result.observations} == {dataset.code}
    new = [observation_record(o) for o in result.observations]
    assert_parity(f"{dataset.code} observations", new, case["observations"], OBSERVATION_IDENTITY)
    assert summary(new) == summary(case["observations"])  # count, country coverage, year range


def test_skipped_areas_match_legacy(parity):
    case, _, _, result = parity
    assert [list(a) for a in result.skipped_areas] == case["skipped_areas"]


def test_missing_source_values_are_exactly_the_identities_legacy_omitted(parity):
    """Every year entry of a mapped area is either a legacy observation or an
    empty source value; nothing else is dropped and nothing is invented."""
    case, dataset, rows, result = parity
    skipped = {code for code, _ in result.skipped_areas}
    entries = [e for row in rows if row["series"] == case["series_code"] and row["geoAreaCode"] not in skipped for e in json.loads(row["years"])]
    empty = sum(1 for e in entries if e["value"] == "")
    assert result.missing_values == empty
    assert len(case["observations"]) == len(entries) - empty == len(result.observations)
