"""Differential test: the orchestrated BIODIV run must reproduce BOTH legacy
routes exactly, the compute route (observed scores) and the impute route
(imputed scores), on the committed UN fixtures.

``biodiv_imputation_cases.json`` was generated by ``generate_imputation_cases.py``
in the old virtualenv at the pinned commit. The Austria rows record the
executable legacy behaviour for a landlocked country (marine filled from the
reference class, three components averaged), which conflicts with the retired
2018 static metadata; that conflict is preserved, not resolved, here. See BIODIV-1 in
docs/methodology-conflicts.md.
"""

import json

import pytest

from sspi.imputation import is_imputed
from sspi.indicators import compute_indicator, registry
from sspi.ingestion.unsdg import normalize_unsdg_dataset
from sspi.metadata import MetadataCatalog
from tests.golden.parity import INDICATOR_CASES, assert_parity, load_cases, score_records, source_fixtures

BIODIV = load_cases(INDICATOR_CASES["BIODIV"])
THINNED_MYS_MARINE_YEARS = set(range(2000, 2003)) | {2010, 2011, 2015} | set(range(2022, 2026))


@pytest.fixture(scope="module")
def observations():
    catalog = MetadataCatalog.load()
    payload = {}
    for path in source_fixtures(BIODIV):
        fixture = json.loads(path.read_text())
        payload[fixture["indicator"]] = fixture["data"]
    return [
        o
        for code in ("UNSDG_MARINE", "UNSDG_TERRST", "UNSDG_FRSHWT")
        for o in normalize_unsdg_dataset(catalog.dataset(code), payload[catalog.dataset(code).source.query_code]).observations
    ]


def variant_observations(observations, variant):
    if variant["name"] == "thinned_mys_marine":
        return [o for o in observations if not (o.dataset_code == "UNSDG_MARINE" and o.country_code == "MYS" and o.year in THINNED_MYS_MARINE_YEARS)]
    return observations


@pytest.mark.parametrize("variant", BIODIV["variants"], ids=[v["name"] for v in BIODIV["variants"]])
def test_orchestrated_run_matches_both_legacy_routes(observations, variant):
    result = compute_indicator(registry.get("BIODIV"), variant_observations(observations, variant), variant["recipients"])

    name = variant["name"]
    assert_parity(f"BIODIV observed scores ({name})", score_records(result.observed_scores, imputation=True), variant["observed_scores"])  # legacy compute route
    assert_parity(f"BIODIV imputed scores ({name})", score_records(result.imputed_scores, imputation=True), variant["imputed_scores"])  # legacy impute route after filter_imputations
    assert sorted({(u.country_code, u.year) for u in result.unscored}) == [tuple(x) for x in variant["incomplete_identities"]]

    observed = {(s.country_code, s.year) for s in result.observed_scores}
    imputed = {(s.country_code, s.year) for s in result.imputed_scores}
    assert observed.isdisjoint(imputed)
    assert sorted(observed) == [tuple(x) for x in variant["observed_only_scores_not_stored_by_impute_route"]]
    assert all(not is_imputed(s) for s in result.observed_scores) and all(is_imputed(s) for s in result.imputed_scores)
    # the compute route's incomplete groups are exactly the raw identities it could not score
    raw = {(o.country_code, o.year) for o in variant_observations(observations, variant)}
    assert sorted(raw - observed) == [tuple(x) for x in variant["observed_incomplete_identities"]]


def test_headline_values_austria_and_malaysia(observations):
    committed = next(v for v in BIODIV["variants"] if v["name"] == "fixture_as_committed")
    thinned = next(v for v in BIODIV["variants"] if v["name"] == "thinned_mys_marine")
    definition = registry.get("BIODIV")

    run = compute_indicator(definition, observations, committed["recipients"])
    scores = {(s.country_code, s.year): s for s in run.scores}
    aut_2020 = scores[("AUT", 2020)]
    marine = next(o for o in aut_2020.inputs if o.dataset_code == "UNSDG_MARINE")
    assert is_imputed(aut_2020) and marine.provenance["imputation_method"] == "ImputeReferenceClassAverage"
    assert marine.value == 36.56867346153846 and aut_2020.score == 0.5858737782051282
    assert sorted(y for c, y in scores if c == "AUT") == list(range(2000, 2024))
    mys_2020 = scores[("MYS", 2020)]
    assert not is_imputed(mys_2020) and mys_2020.score == 0.2972865333333333
    assert sorted(y for c, y in scores if c == "MYS") == list(range(2000, 2026))  # compute route: no year filter
    assert is_imputed(scores[("CHE", 2020)]) and scores[("CHE", 2020)].score == 0.40930980448717946

    run = compute_indicator(definition, variant_observations(observations, thinned), thinned["recipients"])
    scores = {(s.country_code, s.year): s for s in run.scores}
    assert (scores[("MYS", 2001)].score, scores[("MYS", 2011)].score, scores[("MYS", 2023)].score) == (0.18463580000000002, 0.2613001111111111, 0.2972865333333333)
    assert all(is_imputed(scores[("MYS", y)]) for y in (2001, 2011, 2023)) and not is_imputed(scores[("MYS", 2020)])
    assert scores[("AUT", 2020)].score == 0.593088010283688
